### ISSUE TITLE
Generated Classes are not resolved

### ISSUE THREAD

**Issue by eric-ampire** [raamcosta/compose-destinations#1]
Generated Classes are not resolved, but everything compile as expected

<img width="879" alt="Screenshot 2021-09-29 at 11 13 06" src="https://user-images.githubusercontent.com/32017617/135240770-6b0dfb07-bb83-4f7f-aabb-be9166cf8f6c.png">

**Comment by raamcosta** [comment]
Hi Eric :)
I think I know what the problem is: the IDE is likely looking at the generated files. This is a known KSP issue.
As a temporary solution manually mark the folder as a "Generated sources root".
Like this:

![image](https://user-images.githubusercontent.com/80427734/135247398-6302f903-3568-4ecc-933f-6a53b8685cf7.png)

I will change gradle in the next commit so that this is not necessary to do manually. I removed it because it was giving me issues when I was using Jitpack to publish the library, but now I should re-add it.

Thanks!

**Comment by eric-ampire** [comment]
I get it thanks

**Comment by raamcosta** [comment]
I just pushed a commit to fix this for future cloners. 
@eric-ampire you can also just update the local branch and it should work without adding the folder manually.

Thanks for opening the issue 👍  It was important so others don't experience this when trying to build the sample :)

**Comment by eric-ampire** [comment]
Okay great, I'll update my local repo
