### ISSUE TITLE
Support for kotlin value classes as nav args

### ISSUE THREAD

**Issue by jakobulbrich** [raamcosta/compose-destinations#104]
Currently value classes such as `value class UserId(val value: Long)` are not supported as navigation arguments.
They are quite useful to provide an additional layer of type-safety.

For now I can do manual unboxing and boxing during navigation. But it would be nice to have out of the box support for them if they wrap a valid nav arg type.

**Comment by Aidanvii7** [comment]
Worth trying again with Kotlin serialization `@Serializable` annotation on the value class? 🤔

**Comment by raamcosta** [comment]
Hi @jakobulbrich!

Thanks for opening this! It's funny even yesterday I talked with someone using value classes as well, and I made a mental note to not forget.

Will look into this after some stuff (surprise!) that I'm doing atm.

**Comment by raamcosta** [comment]
> Worth trying again with Kotlin serialization @Serializable annotation on the value class? 🤔

Yeah, I'm guessing that will work (I actually have not tried yet) but it requires a specific dependency, so I'll keep this as a future enhancement.

**Comment by pmurph0** [comment]
> > Worth trying again with Kotlin serialization @serializable annotation on the value class? 🤔
> 
> Yeah, I'm guessing that will work (I actually have not tried yet) but it requires a specific dependency, so I'll keep this as a future enhancement.

Unfortunately, it does not work. I get:

``` 
Composable 'NewPostScreen': annotated function cannot define arguments of navigation type if using a 'navArgsDelegate' class. 
```

When annotating my NavArgs class with kotlin serialization `@Serializable`.

**Comment by Aidanvii7** [comment]
@pmurph0 From what I've seen, this means you're declaring navigation arguments in the destination composable as well as declaring a delegate. You can do one or the other, not both.

**Comment by pmurph0** [comment]
@Aidanvii7 
[The documentation](https://composedestinations.rafaelcosta.xyz/destination-arguments/navigation-arguments#navigation-arguments-class-delegate) states that should be possible:

> Note that we can also still receive the arguments in the Composable too if we declare a parameter of the navArgsDelegate class, but you cannot define any other argument of navigation type (you should not need to anyway).

I need the navargs in the composable for my use case and I don't have any other arguments of navigation type in the Composable (I just have a `DestinationsNavigator` and `ResultRecipient` as well)

When I remove `@Serializable` from the NavArgs class, it works fine.

**Comment by pmurph0** [comment]
I think the problem is that any composable param annotated with `@Serializable` is treated as navigation arg type, even if its the type defined as the `navArgsDelegate`.

See `TypeInfo.isCustomTypeNavArg()` function in `com.ramcosta.composedestinations.codegen.commons.TypeUtils`.

I could have a go at a PR to address that.

**Comment by raamcosta** [comment]
@pmurph0 the delegate type is just the place you declare the nav args, it will not be itself a nav arg. So there is no point in annotating it with Serializable. It’s fields are the ones that need to be.

**Comment by raamcosta** [comment]
> I need the navargs in the composable for my use case and I don't have any other arguments of navigation type in the Composable (I just have a DestinationsNavigator and ResultRecipient as well)

Yeah in this case, remove the Serializable from the delegate class itself and receive it as a parameter to the Composable function.

**Comment by efemoney** [comment]
Bumping this. I see the value (pun intended) in having built in support for value classes.

**Comment by Nek-12** [comment]
Bumping this. Just ran into issues trying to use value classes.

**Comment by raamcosta** [comment]
This will be in new versions 1.x.31-beta.
Please give it a try and give me feedback!

This ended up not being as easy as I thought, I ended up making some choices otherwise it would require manual setup from the developer. So, limitations:
- Value class has to have a public constructor 
- Value class has a public non nullable field
- Value class "inner type" needs to be a navigation argument type. This is the one which I believe was always expected but tried to also enable Value classes of Value classes of Value classes (...n times..) of a navigation argument type, but it would be hard to enable this.

In the end, I believe the limitations are ok since the most common scenarios shouldn't have an issue with them.
