### ISSUE TITLE
How to use DestinationsNavigator in case of multiple NavHosts

### ISSUE THREAD

**Issue by arunjoseph-tomtom** [raamcosta/compose-destinations#111]
Thanks for the great library and documentation.

Is it also possible to get 
```
fun navigate(
        direction: Direction,
        onlyIfResumed: Boolean = false,
        builder: NavOptionsBuilder.() -> Unit = {},
    )
```
as an extension to `NavController`?

I use multiple DestinationNavHost approach as in comment
https://github.com/raamcosta/compose-destinations/issues/105#issuecomment-1100651047, and I miss `DestinationsNavigator`. 

Another question -

Is there a possible to create/obtain `DestinationsNavigator` from `NavController` instance so that I can provide to the own `NavigationProvider` interface? and I can add into the `dependenciesContainerBuilder`

**Comment by raamcosta** [comment]
> Is it also possible to get
>
> fun navigate(
        direction: Direction,
        onlyIfResumed: Boolean = false,
        builder: NavOptionsBuilder.() -> Unit = {},
    )
as an extension to NavController?

It's not easy because we use `navBackStackEntry` as well to do the onResume thing. But you can make your own, it shouldn't be to difficult 🙂 
There is a `navigateTo` extension function that receives `Direction` as well. So all it's missing is the check of RESUMED state.

> Is there a possible to create/obtain DestinationsNavigator from NavController instance so that I can provide to the own NavigationProvider interface? and I can add into the dependenciesContainerBuilder

For the same reason, not possible. But your provider can just provide the navController of the parent NavHost. Or you can also manually call the composables and pass lambdas that use that same NavController. Or again, make your own interface that uses that same NavController and pass it in `dependenciesContainerBuilder `.

Lots of options! 🙂 
Hope this helped! I'll close but feel free to add follow up below.
