### ISSUE TITLE
DeepLink resolve

### ISSUE THREAD

**Issue by margarita-v** [raamcosta/compose-destinations#133]
I wanted to clarify the deep link resolve rules. I have no problems with deep links without params or with a defined url scheme, tested on playground project:
`const val SETTINGS_DEEP_LINK_URI = "https://destinationssample.com/settings // works`
the adb command:
`adb shell am start -W -a android.intent.action.VIEW -d "https://destinationssample.com/settings"`
and

`const val SETTINGS_DEEP_LINK_URI = "https://destinationssample.com/settings?id={id}" //works`
add default param to SettingsScreen:
```
@Composable
fun SettingsScreen(
    ...
    id: String = "id"
```
the adb command:
`adb shell am start -W -a android.intent.action.VIEW -d "https://destinationssample.com/settings?id=id"`

From the [docs](https://composedestinations.rafaelcosta.xyz/deeplinks) I've seen a trick with `FULL_ROUTE_PLACEHOLDER` constant but was unable to test it: as far as I understood, the url `"https://destinationssample.com/settings/$FULL_ROUTE_PLACEHOLDER"` should be the same as `"https://destinationssample.com/settings/{id}"` (based on SettingsScreen args), but in fact when I set the url to `"https://destinationssample.com/settings/{id}"`, the following command works:
` adb shell am start -W -a android.intent.action.VIEW -d "https://destinationssample.com/settings/id"` though the same command doesn't work for url `"https://destinationssample.com/settings/$FULL_ROUTE_PLACEHOLDER"` which is supposed to lead to the same screen (only the main app screen is opened, not the settings screen).

Same problem with ProfileScreen from playground, I was unable to test the deep link because it's defined with FULL_ROUTE_PLACEHOLDER. I tried to simplify `ProfileScreenNavArgs` (set only id as a required param) and then changed url to ` DeepLink(uriPattern = "https://destinationssample.com/profile/{id}")`, only this manual url fix helps (for command `adb shell am start -W -a android.intent.action.VIEW -d "https://destinationssample.com/profile/8"`)

Am I missing something? I would appreciate any help!

**Comment by raamcosta** [comment]
Always good questions from you @margarita-v !
Thank you 🙏 

I’ll get to you as soon as I can. Need to test some stuff on my side

**Comment by raamcosta** [comment]
So, you can open the generated Destination and check the `deepLinks` field to see how the generated URL looks when using `FULL_ROUTE_PLACEHOLDER`.

Not sure what happened to you with the ProfileScreen from playground, but you should definitely be able to use it.
After I removed all nav args except id, look at the url:

<img width="617" alt="image" src="https://user-images.githubusercontent.com/80427734/168921971-411e0b9b-cefa-4b88-acf0-962bb1531783.png">

This was using `FULL_ROUTE_PLACEHOLDER`.

In your first example, instead of `"https://destinationssample.com/settings/$FULL_ROUTE_PLACEHOLDER"` do `"https://destinationssample.com/$FULL_ROUTE_PLACEHOLDER"`. Since full route contains also "settings", the URI sent in the deep links, shouldn't when you use that placeholder.

**Comment by raamcosta** [comment]
Let me know if this makes sense, maybe retry on your side and let me know 🙂

**Comment by margarita-v** [comment]
Thanks a lot! I see that I should check the generated deep link url first, now it works!
