### ISSUE TITLE
Multi Module Setup

### ISSUE THREAD

**Issue by buntupana** [raamcosta/compose-destinations#149]
Just wondering how could be a proper multi module setup with your library. Is there anyway to use Directions classes between different features modules and navigate between them??

How should gradle be setup in library (features) modules?

Thanks!

**Comment by raamcosta** [comment]
Hi @buntupana !

I have two examples of this in two forks of two known projects in Android community.
You can read more here:
https://composedestinations.rafaelcosta.xyz/codegenconfigs#multi-module-configs

It also contains the links to those forks. They are not super up to date with latest library versions so there may be some small adjustments but the overall idea is the same.

**Comment by buntupana** [comment]
Thanks for the quick reply and for this awesome library @raamcosta 

I've been checking the libraries and it looks that it requires a quite amount of coding to setup the project, not that easy like a mono module project, or maybe I didn't understood pretty well.

I'm trying to figure out if there is a way to inject `DestinationsNavigator` in `ViewModel` instead the `Composable`, is there a easy way to do it with for example `Hilt`??

**Comment by raamcosta** [comment]
Yea it definitely takes more setup compared to single module apps (or just a single module for navigation).

About navigators inside the ViewModel, it’s usually not recommended because they hold inside stuff that can be cleared before the ViewModel is. And so you’d be leaking them.
I have been toying around with the idea of making this possible but it will envolve a kind of event bus in the middle that listens for nav events and proxies them (indirectly) to a component in the MainActivity  that does the actual navigations.
No ETA though you can also do it internally, which I’ve seen before in some blog posts.

**Comment by raamcosta** [comment]
@buntupana, I’m closing this but please let me know down below if I can help you any further 🙂

**Comment by buntupana** [comment]
@raamcosta I'm trying to setup a Project with two features modules (`Feature1`, `Feature2`) and the App module.

What I think is the best approach is to create Navigator interfaces for every module so from `Feature1` I could navigate to `Feature2` and vice versa and use di to inject them into the modules. The di module will be feed in the app module.

So for example I could go from `HomeScreen` (Feature1 module) to `DiscoverScreen` (Feature2 module) using `Feature1Navigator`

So far I have two problems:

1. Auto generate a Graph with destinations from different modules, is this even possible? I had to create it manually:

       object NavGraphs {
    
        val root = object: NavGraphSpec {
            override val route = "discover"
    
            override val startRoute = DiscoverScreenDestination routedIn this
    
            override val destinationsByRoute = listOf<DestinationSpec<*>>(
                DiscoverScreenDestination
            ).routedIn(this)
                .associateBy { it.route }
        }

2. Inject the auto generated `DestinationsNavigator` in the navigator implementation, I have no idea how to inject the autogenerate one.

        class Feature1NavigatorImpl @Inject constructor(
            private val navigator: DestinationsNavigator
        ) : Feature1Navigator {
         
            // Discover Screen is in Feature
            override fun toDiscoverScreen(id: String) {
                navigator.navigate(DiscoverScreenDestination(id))
            }
        }

Do you have an idea how I could solve this problems??

Cheers!

**Comment by raamcosta** [comment]
Hey @buntupana !

First of all, forget about `routedIn` calls. This is only useful if you want to have destinations belonging to multiple NavGraphs. So when manually building the NavGraphs, just don't call `routedIn` unless you really need to.

1.
There are two possible setups for multi module: each feature module outputs a navigation graph (ksp config mode "navgraphs"), or each feature module outputs a single destination (ksp config mode "destinations").  In both cases, you need to manually setup the "root" nav graph that gets passed to `DestinationsNavHost` to be able to gather these navgraphs / destinations from feature modules.

2.
Why do you want to use DI framework to pass navigators? Where do you want to inject them to? If you want to inject them into ViewModel, like I said before, you shouldn't. If you want to inject to Composable functions, then using DI framework won't work since it's a function and not a class?

Instead, use `dependenciesContainerBuilder` parameter of `DestinationsNavHost` to "inject" the navigators. Inside the  `dependenciesContainerBuilder` lambda, you'll have access to `NavController` (or `DestinationsNavigator`). So you can just instantiate your feature modules navigators and pass them using `dependency` functions.

```kotlin
    DestinationsNavHost(
        //...
        dependenciesContainerBuilder = { //this: DependenciesContainerBuilder<*>
                              // 👇 this will only provide Feature1Navigator for HomeScreen, but you can also
            // use a NavGraphSpec if you want to provide it for all destinations of certain Navigation graph
            dependency(HomeScreenDestination) { Feature1NavigatorImpl(destinationsNavigator) }
        }
    )
```

**Comment by buntupana** [comment]
@raamcosta wow...that works just perfect. Your are right about the navigation stuff in ViewModel, I was just playing around about some ideas. I guess there is no a quick and simple way to setup a multi module project so far, however you made the process much easier with compose destinations.

Thanks a lot!!
