### ISSUE TITLE
Passing `CoroutineScope` to Destination/ViewModel

### ISSUE THREAD

**Issue by mainrs** [raamcosta/compose-destinations#170]
Hello!

I've read through the documentation and it seems that the navigation arguments are only meant for simple data (types). I need to pass a `CoroutineScope` to my ViewModel. It looks like the delegate functionality is the way to go. But since it depends on `SavedStateHandle`, I cannot pass down the scope.

The problem arises when using a ViewModel inside a BottomSheet. The sheet has a save button that launches the database transaction and pops the navigation stack. Since the ViewModel gets destroyed, the database transaction doesn't fully happen.

I solved it by using DI and providing an application-wide `CoroutineScope`. but I'd rather somehow pass down the parents scope to the BottomSheet or its ViewModel.

**Comment by raamcosta** [comment]
That means you’d pass a scope from the place you call NavHost. But this is the only place you can know for sure is run before your bottom sheet.
Because the app process can be restored and start immediately on the bottom sheet screen. So you wouldn’t have a scope from the previous screen in this case.

The alternative is to make a nested navigation graph containing all screens you want to scope your CoroutineScope in and use a ViewModel ties to that nested nav graph instead. This way your coroutine scope from that VM will leave longer than the bottom sheet screen.

**Comment by raamcosta** [comment]
Hey @mainrs ,

I’ll close this since no new replies were added, but still let me know below in the comments if you managed to make it work 🙂
