### ISSUE TITLE
Navigate to Nested Screen in Different Graph

### ISSUE THREAD

**Issue by parveensharmayml** [raamcosta/compose-destinations#172]
Hi, Thankyou so much for this wonderful library. But I did not find any documentation regarding navigation to nested screen in different graph and move back on same destination. Can you please provide some information regarding the same ?
**UseCase:**
(Refer to your library sample)
1. User can navigate to SettingsNestedDestination under Settings Tab from TaskScreen (Tasks Tab)
2. If User presses back button on SettingsNestedDestination (it was navigated from Tasks Tab by some random nested screen) should be navigated to previous destination (whatever tab it is).
3. It User press Tasks Tab in such condition it should retain state for that case as well.
4. Right now app gets killed from any tab if there is no previous backstack entry associated with it. Please provide some way where a user press back button on any tab should navigate to Initial Tab (Tasks Tab) and than app should get killed. 

@raamcosta Thankyou again for this amazing work.

**Comment by janseeger** [comment]
Hello @raamcosta,

I think we have a similar problem, where navigating within a Graph of multiple Nested NavGraphs results in the BackStack state not being properly saved and restored afterwards. This occurs when navigating within one Nested Graph, as well as when crossing between Nested Graph boundaries.

We do have [altered your Sample project](https://github.com/sipgate/compose-destinations/tree/nested_navgraphs) to demonstrate the issue.

Steps to Reproduce:
* Task List -> Select Random Task
* Navigate to the Settings Tab
* Navigate back to the Tasks Tab

Thank you very much for this spectacular library!

**Comment by raamcosta** [comment]
Hey guys 👋

First things first, this is not an issue or a special behaviour with this library. This would be the same with vanilla compose navigation.

The reason this happens in my sample is the popUpTo I do on each bottom bar item click. I literally clear the backstack explicitly, so we can say that this is the UX I wanted for the sample app.

The idea is to not build a large stack if the user clicks multiple times on multiple tabs. Now there is probably a way to save only the last destination every time instead of clearing all, but I’ll leave it to you guys to find out 😁 remember that we’re still using the same APIs as vanilla compose navigation so you can easily adapt any solution you find in Google.
When I have some time I can also check this, maybe this next weekend 🙂

**Comment by raamcosta** [comment]
I just run the nowinandroid and tivi projects which are examples provided by google and Chris Banes, and they both work the same: when user backs after changing tab in the bottom bar, it goes to the start destination of the app.

To do that, in the sample, replace:

```kotlin
popUpTo(NavGraphs.root) {
    saveState = true
}
```

with 

```kotlin
popUpTo(NavGraphs.root.startAppDestination) {
    saveState = true
}
```

**Comment by tigerxy** [comment]
Hey, 

I found our error that @janseeger described. We were navigating between destinations and not between nested NavGraphs. Maybe you can add this in your documentation.

Best regards and thanks again for your amazing libary!

By the way, are you going to visit DroidCon Berlin? If so, it would be nice to meet you at our sipgate booth!

**Comment by raamcosta** [comment]
I would love to, but I have my hands full with my son who is just 8 months, so I can’t leave him all to his mom 😅

Thanks for the kind words and wish you a great droidcon 🙂

**Comment by raamcosta** [comment]
I think I mention somewhere in the bottom bar example that we can also have nested nav graphs as destinations of bar item, but I should definitely explain it in more detail 🙂
