### ISSUE TITLE
Cross-graph navigation

### ISSUE THREAD

**Issue by keeperus** [raamcosta/compose-destinations#188]
I've got a parent `MainGraph` and a child `BottomNavGraph` graphs. 
As you can see from the names these graphs are responcible for the global navigation and the bottom navigation tabs.
Is it possible to make a clean navigation from the BottomNavGraph screen to another MainGraph screen?
```IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/category_screen/4 } cannot be found in the navigation graph NavGraph(0x99a4dbf8) route=bottom startDestination={Destination(0x442b361f) route=home_screen}```
home_screen - BottomNavGraph holder.
I'm navigating from the CategoriesScreen(BottomNavGraph tab) to the CategoryScreen(MainGraph).

**Comment by raamcosta** [comment]
Hi 👋 

Im guessing you have multiple DestinationsNavHost calls?
Common misconception is that Navigation graphs are one to one with NavHosts. This is not true. One NavHost receives a top level nav graph but that one can have multiple neste graphs.

I need to know more about your case to help you, but yea I’m both cases you can always navigate just like with official compose navigation, just with compose destinations improvements.

**Comment by ModAlpha** [comment]
I have the same case here
I have root graph and nested graph for bottom nav bar, I need to navigate from the nested graph to screen from the root graph

**Comment by raamcosta** [comment]
> I need to navigate from the nested graph to screen from the root graph

If it’s correctly nested, you can just do it. How many DestinationsNavHost calls do you have?

**Comment by ModAlpha** [comment]
firstly I have two, I have screen that hold bottom bar and the nav graph

@Destination
@Composable
fun MainScreen(
    rootNavController: DestinationsNavigator,
    mainScreenViewModel: MainScreenViewModel = getViewModel(),
) {

    val navController = rememberNavController()
    val scaffoldState = rememberScaffoldState()

    val user by mainScreenViewModel.user.collectAsState()


    Scaffold(
        scaffoldState = scaffoldState,
        topBar = {
            MainScreenTopBar(scaffoldState, rootNavController, true, user)
        },
        drawerContent = {
            MainDrawer(
                navController = rootNavController,
                drawerState = scaffoldState.drawerState,
            )
        },
        drawerBackgroundColor = Primary,
        drawerShape = DrawerShape,
        bottomBar = {
            MainBottomBar(navController)
        },
    ) {
        DestinationsNavHost(
            navController = navController,
            navGraph = NavGraphs.main
        )
    }

}

**Comment by ModAlpha** [comment]
what I need to achieve is that I have the auth flow in the root nav graph and I depending if the user logged in or not I should take him to home screen

the home screen have bottom bar, so I created main nav graph and put the main screens of the bottom bar in it, but then I need to navigate from the main nav to root nav so I faced this probelm

**Comment by raamcosta** [comment]
If you really need two NavHosts as opposed to just showing or hiding the top and bottom bars depending on the current visible screen, then you need to pass the NavController from the root NavHost to the main one.

In your case, all you need is in MainScreen to add a “navController: NavController” parameter to it. Since it belongs to the root nav, it will receive that NavController.
Then, in order to pass this NavController of the root to whichever screen of the main nav graph that needs it, you can either manually call them or use “dependencyContainerBuilder” parameter of the NavHost.
You can see these two approaches in this link:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters

(Scroll down a bit until you see two links: one for manually calling composables and one for dependency container). Just know that if you go with dependencyContainerBuilder approach you need to wrap your root nav controller in some other class type. Otherwise we have no way of knowing which nav controller the screen wants (since they have the same class), something like:
“class RootNavController(val value: NavController)”

So after that, your screens that need to use this can request a parameter of that type, and compose destinations can use the dependency container to provide it.

**Comment by ModAlpha** [comment]
okay, thanks, it worked

**Comment by raamcosta** [comment]
I'll close this then. @keeperus let me know if you still need any help! I'm available :)

**Comment by keeperus** [comment]
Yeah. Thank!
Sorry for the late reply.
I've been pretty busy last month :(
