### ISSUE TITLE
Navigation using Uri

### ISSUE THREAD

**Issue by eric-ampire** [raamcosta/compose-destinations#2]
The Jetpack navigation component support navigation via Uri, and it seems like compose destination doesn't support navigation with URI yet, there is an alternative way ?

**Comment by raamcosta** [comment]
Hmm I guess the problem here relates to the usage of `DestinationsNavigator`, correct?

This is an easy fix, all we need to do is add a method to the `DestinationsNavigator` interface that receives a Uri and implement it calling the corresponding method in the `NavController`.

In the meantime, you can simply take the `NavController` as a parameter to the Composable and that will also allow you to navigate with Uri. 
So to be honest I'm torn as to whether or not to implement this method in `DestinationsNavigator`.
Because I'd like to keep this wrapper as thin as possible. I think for more "exotic" use cases where you really want to be navigating inside your app with deep links (this is the only use case to navigate with a Uri right?) maybe it is ok to depend directly on `NavController`?

What do you think?

**Comment by eric-ampire** [comment]
If the code generation is still compatible with the navController then it
can be used but it would be interesting to mention this somewhere in the
documentation so that the user can know in which situation he has to use
the navController or not, because the first reflex is to use the method
from DestinationNavigator : )

**Comment by raamcosta** [comment]
Yes, both are valid as arguments to Destinations.
The wrapper is useful if you want to test or preview these Composables, but you can always just call an overload version of the Composable that only receives lambdas and state.

But you're right that this deserves a mention somewhere. I'll think about it. Thanks for the feedback 👍

**Comment by raamcosta** [comment]
Updated wiki to mention this, so I'm closing this issue. Let me know if there is actually something else you'd want to see mentioned or fixed.

https://github.com/raamcosta/compose-destinations/wiki/Navigation#navigating
