### ISSUE TITLE
Setting startDestination with argument doesn't work

### ISSUE THREAD

**Issue by cloneconf** [raamcosta/compose-destinations#20]
Hello,
I want to override the start destination and that destination does have an required argument.

```kotlin
DestinationsNavHost(navController = navController, startDestination = PostScreenDestination(1234))
```

But when i pass the argument it shows error in the IDE: 
```
Type mismatch.
Required: Destination
Found: Routed
```

How i should do it?

Thanks in advance.

**Comment by raamcosta** [comment]
Hi @cloneconf ! 👋 

Thanks for taking the time to report.
Start destinations cannot have mandatory arguments, which makes sense because how would you pass them if the app starts there? 
So your solution is to make the argument not mandatory, by providing the default value (in your example, that would be `1234`)

To do that, go to your `PostScreen` composable and add it:

```kotlin
@Destination
@Composable
fun PostScreen(
    argName: Int = 1234
) {
//...
}
```

Then in the NavHost call:

```kotlin
DestinationsNavHost(navController = navController, startDestination = PostScreenDestination)
```

Let me know if that answer works for your use case! 🙂

**Comment by cloneconf** [comment]
Thanks @raamcosta for the fast reply :)
> Start destinations cannot have mandatory arguments, which makes sense because how would you pass them if the app starts there?

Actually it does make sense to provide argument in my case :/

For example:
I want to show an post when the user hit my website for example:
https://example.com/article?id=1234
and i don't want to keep the home screen in the backstack so the user can easily close the app when he done reading :)

You guess it, the id properly will be not fixed.

I was able to done this in the vanilla NavHost.


```kotlin
NavHost(navController, Screen.Post.byId(1234))
```

```kotlin
const val ARG_ID = "id"

sealed class Screen(val route : String) {
    object Post : Screen("post_screen/{$ARG_ID}") {
        fun byId(id : String) = "$route/$id"
    }
}
```

Maybe enabling string paths will be the solution.

**Comment by raamcosta** [comment]
Ahh so this is a deep link thing?
We have support for deep linking not sure if you've seen it.

I believe it will work exactly as you want out of the box. And this way you don't need to override the start destination at runtime.

That said, it's good to know that this is possible with vanilla NavHost. I'll probably make changes to support it too. But, if I'm understanding your use case correctly, deep linking support is the best way for you anyway.

If that seems interesting to you, maybe you can check these files:
- intent filter part: [AndroidManifest.xml](https://github.com/raamcosta/compose-destinations/blob/main/app/src/main/AndroidManifest.xml)
- deep links inside annotation: [ProfileScreen.kt](https://github.com/raamcosta/compose-destinations/blob/main/app/src/main/java/com/ramcosta/samples/destinationstodosample/destinations/profile/ProfileScreen.kt)

Let me know if this helps! As I said, expect the lib to support `Routed` instead of `Destination`. Thanks for point that out 👍

**Comment by cloneconf** [comment]
Hi @raamcosta,
> That said, it's good to know that this is possible with vanilla NavHost.
Sorry but doesn't seem to work :'(

I don't know what happend!
Please can you tell me if this code correct?
```kotlin
NavHost(navController = rememberNavController(), startDestination = "post_screen/1234") {
    composable(
        "post_screen/{id}"
    ) { Text(it.arguments?.getInt("id").toString()) }
}
```

Cause it throws really strange error:
```
java.lang.IllegalArgumentException: navigation destination 1298737267 is not a direct child of this NavGraph
```

Maybe this is a bug in the navigation itself!
Or maybe it wasn't for that use case :/
What you think?

**Comment by raamcosta** [comment]
Ahh I was already working on it ahahah

But yes, I also got to the point where it was crashing exactly like that.
Another reason why we cannot trust all these strings we need to use for vanilla compose navigation 🙂 

Glad we got to the bottom of this. If there is anything else I can help you with, please do let me know!

**Comment by cloneconf** [comment]
Thanks for you very much :)
