### ISSUE TITLE
How to use navigator outside of composable?

### ISSUE THREAD

**Issue by Jalson1982** [raamcosta/compose-destinations#203]
At first thanks a lot for great library. This is more like question then. I need your opinion about this @raamcosta . We have something like server side rendering where we get a lot of urls that are basic deeplink and once user click on button for example that have attached this deeplink it will navigate where it needs to navigate.  Basically, idea is that composable get something like action manager. This action manager will take that url and first check is it valid url or not. Then will check is there any action handler that can handle it . If yes then it will use navigation to perform navigation action. In this setup i do not want in every composable to pass navigator to action manager as dependency  I would like somehow to use it directly in action manager. Is it even possible to get reference to navigator in some class that is not composable function? Thx a lot in advance!

**Comment by raamcosta** [comment]
Hi 👋 

This is all about scoping. As long as you make sure your nav controller isn’t held somewhere that makes it impossible to be garbage collected when it should, then all is fine.

So if you pass the nav controller (or DestinationsNavigator which itself has a reference to the NavController so it’s the same) to some component that lives longer than the activity, it will leak and it will stop working.

It is ofc possible, you can call rememberNavController before DestinationsNavHost, then pass that NavController to it, and then you can pass it to some other component (again, making sure that other component doesn’t live longer than the activity).

The reason this is tricky is that, imagine:
- You pass the NavController to the component 
- You clear it when it should be cleared
- Soon enough some other NavController will be created and you pass that new one

For the most part, this works, but imagine your event from the server comes right after you cleared the previous NavController. Then you cannot navigate right away, so you need to wait for the new NavController to be ready.

Sorry for the unorganised thoughts, I’m on my smartphone 😅
Let me know if I can help you any further.

Btw this would be the same with official compose navigation, nothing is more difficult because compose destinations, just wanted to make that clear 😁

**Comment by Jalson1982** [comment]
Hello. Thx for answer. I was thinking is it possible to have one instance of navigator that will live as long as application do. We are using this also with push notifications for example and it is very neat to have one centralized place that will handle navigation. When we get for example push notification in data object it will contain url. That url is passed to action manager. Then action manager do all what needs to do before navigate ( check if url is valid, check is it firebase deep link or normal one, check wich action resolver can handle it, check if user is logged in) and than if all fine on last step it takes navigator and handle navigation. So composable will have access to action manager and will pass that url to action manager. And composable does not care what action manager will do. We made it in ios and react native and now looking for best solution with this awesome lib and jetpack compose. I think as I wrote previously it will be little strange every time when call action manager to pass navigator than pass it further down. I hope that I explain very well general idea and what we try to achieve. Btw thanks for reply one more time!
