### ISSUE TITLE
Passing lambdas to BottomSheet destinations

### ISSUE THREAD

**Issue by cj1098** [raamcosta/compose-destinations#213]
I see lambdas aren't a supported nav destination type. Is there a suggestion for how to go about this? Feels like BottomSheets would definitely need some mechanism for this

Wanted to mark this as a question but didn't have the option, sorry!

**Comment by raamcosta** [comment]
Hi @cj1098 

It’s impossible to use lambdas as navigation arguments (I.e arguments passed from one screen to the other) as these have to be serializer and you cannot serialize/deserialise lambdas since that would create a new instance and so the previous screen wouldn’t be notified.

Do you want to send lambdas from previous screens or from the NavHost level (i.e where you call DestinationsNavHost)? The latter it’s possible, check here:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters#manually-call-your-screen-composable

**Comment by raamcosta** [comment]
Let me know if this helps 🙂

**Comment by cj1098** [comment]
Thanks!
