### ISSUE TITLE
Erroneus dependency on material design in DestinationsNavHost.kt

### ISSUE THREAD

**Issue by vfsfitvnm** [raamcosta/compose-destinations#23]
Hi!
The generated `DestinationsNavHost.kt` actually depends on material design:
```kt
import androidx.compose.material.*
```

Even if none of the material components are used (of course I'd say!), it breaks my build as `androidx.compose.material` is not a dependency of my application.

I guess that line should be removed!

**Comment by raamcosta** [comment]
Hi @vfsfitvnm 👋 

Thanks for reporting.
Yes, you are right, this issue was already fixed in branch `main-multiple-cores` which will deal with dependencies in a much better way and will be the branch that will originate the next release version.

This will be a pretty big release that will change a lot of internal things and some minor APIs (also adds new features like being able to use Parcelables as navigation arguments, etc). So it will take me some time to release as I want to update all documentation on the wikis, etc.

Until then, I hope this doesn't block you. If you are still in the testing phase, maybe you can temporarily add that dependency.

Sorry for the inconvenience and thank you so much again for reporting!

**Comment by vfsfitvnm** [comment]
Hi, thanks for the quick reply!
I just added the dependency as you said 😌
