### ISSUE TITLE
Multiplatform Support

### ISSUE THREAD

**Issue by jimgoog** [raamcosta/compose-destinations#24]
Support for Compose Multiplatform apps is not indicated in the README.

**Comment by raamcosta** [comment]
Hi @jimgoog 👋 

There is no indication because there is no multiplatform support.
This library is for Android only, as it is a wrapper to the Android compose navigation library.

That said, it doesn't mean you cannot use it in a multiplatform project. If navigation is not part of your shared code, then each platform you are targetting can handle its own navigation. In that case, you can use this library on the A

**Comment by raamcosta** [comment]
If there is something related with the issue that I have not addressed, please let me know or reopen it.
