### ISSUE TITLE
Provide arguments to start destination? 

### ISSUE THREAD

**Issue by omsamara** [raamcosta/compose-destinations#247]
Hi I've seen some similar issues but I haven't seen a conclusion yet that really makes sense. I'm trying to use this library just a small portion of our app (one flow). So when I launch the "start destination" I want to provide that start destination with a bunch of information from the activity it came from (really just one view model). 

Is this possible? Or am I being optimistic trying to use this library for just one flow of the app

**Comment by raamcosta** [comment]
Hi @omsamara !

You can always pass anything you want from your activity, but these won't be considered "navigation arguments".
Check this:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters

And since you mentioned ViewModel, check this too:
https://composedestinations.rafaelcosta.xyz/common-use-cases/providing-viewmodels
