### ISSUE TITLE
DestinationsNavTypeSerializer should accept nullable parsed value

### ISSUE THREAD

**Issue by alexzaitsev** [raamcosta/compose-destinations#257]
Please consider the next example:

```kotlin
@NavTypeSerializer
class AddressSerializer : DestinationsNavTypeSerializer<Address> {

    override fun toRouteString(value: Address): String = when (value) {
        is Address.Eth -> "eth,$value"
        is Address.Zil -> "zil,$value"
    }

    override fun fromRouteString(routeStr: String): Address {
        val (network, value) = routeStr.split(",")
        return when(network) {
            "eth" -> Address.Eth(value)
            "zil" -> Address.Zil(value)
            else -> { }
        }
    }
}

```
In such cases naturally I would like to return `null` on `when.else` case. However, that not possible. That forces me to create some `Address.Error` subclass. 
How it should work if null is accepted is a good question. If argument on the destination is not nullable but parsing failed - what should we do? Throw RuntimeException? I'd like to handle it somehow.

**Comment by raamcosta** [comment]
Hi @alexzaitsev !

If you really want to avoid crashes, your best bet is to consider an enum entry like `Address.Unknown`.

Also, are you expecting to use this serializer to parse a string coming from outside? Meaning, coming from other than the `toRouteString`? Because if not (most times), then you can throw exception yourself in the else. It will never happen that you receive something in there that is not a match for either "eth" or "zil" because you returned the string you get there on the `toRouteString`.

**Comment by alexzaitsev** [comment]
Makes sense. Thank you @raamcosta !
