### ISSUE TITLE
Destination shared types between destinations with arguments and without

### ISSUE THREAD

**Issue by MitchellGRead** [raamcosta/compose-destinations#260]
Hello 👋 Just a question I had around destination types and having a shared object between ones that have arguments with ones that do not.

My use case is the following:
I have a few screens with are accessed from a bottom navigation bar. What I am running into is if one of these bottom navigation screens take some navigation argument then we can not represent a shared bottom navigation destination.

For code reference, I have something like the following:
```
enum class BottomNavDestination(
    @StringRes val displayName: Int,
    val direction:[what type should this be?],
    val icon: ImageVector
) {
    ScreenA(
        displayName = R.string.ScreenA,
        direction = ScreenADestination,
        icon = Icons.Default.Home
    ),
    ScreenB(
        displayName = R.string.ScreenB,
        direction = ScreenBDestination(someFlag = false), 
        icon = Icons.Default.Waves
    ),
    ScreenC(
        displayName = R.string.ScreenC,
        direction = ScreenCDestination,
        icon = Icons.Default.DirectionsRun
    );
}
```

As we can see `ScreenB` takes some navigation argument which we would want to set as false in navigation from the bottom bar. This gives this destination of TypedDestination<T>, while the other screens are of DirectionDestination (TypedDestination<Unit>). 

So my question is what type should the direction be in this scenario? Doing something like `TypedDestination<*>` or `DestinationSpec<*>` puts required logic in where we create these navigation items. Something like `Direction` was what allows for the above implementation, however, it has the caveat of this direction losing its original type of `ScreenBDestination`.

Wondering your thoughts on this and if I am going about this the wrong way 😅

**Comment by raamcosta** [comment]
Hi @MitchellGRead ! 👋 

First of all, sorry for taking some time to answer you. Reason is that I needed some time to check in the IDE what would be the best approach in this case.

As you pointed out, the only type that accepts this is `Direction`. I didn't get what exactly is the problem of losing the original Destination type. Can you explain this?

The only caveat to me of using Direction is how you check if this item is selected.. Because Direction doesn't have original route, only the route used to navigate (the one which has the arguments resolved). So this route won't match the one we get on `navController.currentBackStackEntryAsState()`. Another question is if you have a destination that has arguments in the bottom navigation bar, then since it has arguments, I'm guessing you will be navigating to it from another place where actualy the "someFlag" will be true instead right? And in that case would you want to consider the item selected or not?

These are all questions you need to answer, and I can help with specific questions but I won't be answering these for you since they depend on your requirements.

Just keep in mind also these questions are the same if you use official compose navigation. Sure you wouldn't be talking about Destinations, Directions and such, but even with String routes, the same problem exists.

I'll close but let me know below how you solved this 🙂
