### ISSUE TITLE
Start destination that requires arguments

### ISSUE THREAD

**Issue by qbosst** [raamcosta/compose-destinations#281]
Is there a way to set a start destination that requires arguments? 

I have a splash screen that will dynamically choose which start screen should be shown. Some of the destinations will require arguments that the splash screen will provide.

The start destination requires an instance of type route, but the invoked destinations return an instance of destination.
![image](https://user-images.githubusercontent.com/60557521/198873304-57dc416a-7b27-4398-adce-52c5951c1676.png)

Thanks

**Comment by raamcosta** [comment]
Hi @qbosst!

Your start destination cannot have **navigation** arguments because navigation arguments come from the previous destination. And for the start destination, there is no previous destination.

So.. either make your splash screen your start destination always and then it navigates to other passing the nav arguments needed, or since your splash screen comes before you even call the DestinationsNavHost, then when calling your start destination, your argument is not really a navigation one. In that case, you don’t use navigation argument constructs, instead you wanna pass whatever you need directly from the NavHost level. 

With compose destinations, you have two ways to do this depending on the situations. Check it here:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters

**Comment by raamcosta** [comment]
Let me know if this helped below! 🙂
