### ISSUE TITLE
Inject DestinationsNavigator into ViewModel

### ISSUE THREAD

**Issue by Regjoz** [raamcosta/compose-destinations#302]
Hello firstly thank you for the great job in this library.

I have a question about navigation and how It could be solved.

In my opinion the navigation should be responsibility of the ViewModel and not of the view.

Is there a safe way to pass DestinationsNavigatiom directly to the ViewModel  without pass explicity from the view with a setter?

Thanks

**Comment by raamcosta** [comment]
Hi 👋 

I would swear I had already answered this issue, sorry 😅 

> Is there a safe way to pass DestinationsNavigatiom directly to the ViewModel without pass explicity from the view with a setter?

No, and you shouldn't do it even with a setter. DestinationsNavigator holds reference to the NavController so it shouldn't leave the UI (same as with official compose navigation).

Usually what I see people doing is having some sort of channel where they send navigation events from the ViewModel and they do the actual navigate call in the UI.

Also just to challenge this idea:
> In my opinion the navigation should be responsibility of the ViewModel and not of the view.

What if your screen is a tablet and instead of navigating you want to show a 2 pane layout? Official guidance says you should navigate from the UI because only UI knows what exactly it wants the UI to look like depending on different device configurations etc.
