### ISSUE TITLE
Nested graphs navigation

### ISSUE THREAD

**Issue by mnhyim** [raamcosta/compose-destinations#310]
Hi, played around with your library and found it very useful but I have a question about nested navigation. Suppose I have an app with this navigation design 

![image](https://user-images.githubusercontent.com/34624746/205570956-fc6c5387-911d-40e0-945c-d34077079ef5.png)

Is there a way to navigate from (A-A) to (C-D)? When I tried to navigate from (A-A) to (C-D) with screen (B) as the RootNavGraph starting scren it throws an error about finding NavGraph. But If I set the RootNavGraph start to (DestinationsNavHost A) I can navigate from (A-A) to(C-D). Is this the intended behaviour? Thank you.

[Example](https://github.com/mnhyim/research/tree/main/research_destination/src/main/java/com/mnhyim/research_destination)

**Comment by raamcosta** [comment]
Hi @mnhyim !

Just my initial thoughts:

- Are you sure you **need** all these DestinationNavHost? Note that nested graphs **!=** as multiple NavHosts! You can have nested graphs all within the same NavHost and that is generally recommended except if you have some very specific requirements;
- This navigation logic is the same as with official compose navigation. My library is not interfering with anything here.
- Each of these NavHosts is associated with its own NavController and each of these can only navigate to immediate child destinations (given that you have multiple NavHosts. With a single NavHost, then the NavController could navigate multiple levels deep because all graphs and destinations belong to it)
So for example:
    - NavController associated with "root" NavHost can only navigate (again: in your case) to destinations A, B, C and D (the ones which are in the first level of course of this graph ofc).
    - NavController associated with "C" NavHost can only navigate to its D, E and F destinations.
- Do you have a "top level" / "root" NavGraph for each of these DestinationNavHosts? You need a NavGraph without any parent for each of these. You don't want to pass NavGraphs.root to root NavHost, and NavGraphs.C to C NavHost if NavGraphs.C is a nested graph of root. With multiple NavHosts, each NavGraphSpec passed in should not be nested in any other NavGraph. Each of these operate as totally independent things, hence why you need multiple NavControllers :)

**Comment by raamcosta** [comment]
Closing since it is stale for a while. @mnhyim let me know if I can help any further!
