### ISSUE TITLE
public function exposes its internal parameter type containing declaration

### ISSUE THREAD

**Issue by epool** [raamcosta/compose-destinations#316]
Hi! 👋🏼 I have the following destination which uses a `internal` ViewModel

```kotlin
@Destination(
    navArgsDelegate = MyViewModel.ViewState::class,
)
@Composable
internal fun MyScreen() {...}
```
where `MyViewModel.ViewState` looks similar to this
```kotlin
@HiltViewModel
internal class MyViewModel @Inject constructor() : ViewModel() {
    data class ViewState(
        ...
    )
}
```
but I'm getting this error when the destination is generated
```
e: ../MyScreenDestination.kt: (42, 25): 'public' function exposes its 'internal' parameter type containing declaration MyViewModel
``` 
```kotlin
public object MyScreenDestination : TypedDestination<ViewState> {
    ...
    override fun invoke(navArgs: ViewState): Direction = with(navArgs) { // <====== The error is HERE!
        invoke(...)
    }
```

Is there a way to make the destination visibility the same as the view model? 🤔

Thank you in advance! 🙌🏼

**Comment by raamcosta** [comment]
Hey!

>Is there a way to make the destination visibility the same as the view model? 🤔

No, but you can make Destination visibility the same as the Composable you annotate. This makes sense because the generated Destination really doesn't have anything to do with the ViewModel. You might not even be using VM in the first place.

So if that's ok to you, you can make the Composable you annotate with `@Destination` internal and then use:

```gradle

    ksp {
        // If set to "true" will use the annotated composable's visibility in the generated Destination
        // otherwise, Destinations will always be public in this module
        arg("compose-destinations.useComposableVisibility", "true")
    }
```

OR you can make your NavArgs publicly accessible. This also makes sense because why do you want to tie navigation arguments of the Destination to the ViewModel? Navigation arguments is something that should stand on its own. Your ViewModel ViewState can grow a ton while the NavArgs are the same all along, so I wouldn't make my NavArgs a class which I call "ViewState". I probably wouldn't put my NavArgs inside ViewModel either.

**Comment by epool** [comment]
Thank you! 🙌🏼
