### ISSUE TITLE
java.lang.IllegalArgumentException: Destination cannot have the same route as graph NavGraph(0xe7fd39a7) route=dashboard startDestination=0x0

### ISSUE THREAD

**Issue by rezyfr** [raamcosta/compose-destinations#324]
Hello,
I tried to implement compose-destination on a multi-module project. 
However, it crashes every time the app tried to open the first page (I haven't known about the other page since it crashed on the start) with Exception: java.lang.IllegalArgumentException: Destination Destination(0xe7fd39a7) route=dashboard cannot have the same route as graph NavGraph(0xe7fd39a7) route=dashboard startDestination=0x0
Below is the implementation of the NavGraphs
![image](https://user-images.githubusercontent.com/22698234/210055302-d595624f-ea98-491d-849c-6e31ebc4f2d4.png)
![image](https://user-images.githubusercontent.com/22698234/210055343-4981fd67-056d-4d0d-8a64-e115aecb02ca.png)
![image](https://user-images.githubusercontent.com/22698234/210055534-bb73c47c-5008-4c1d-bf77-a64fa3b17ba8.png)

I looked up  the issues section and haven't gotten any enlightenment

**Comment by raamcosta** [comment]
Hi @rezyfr !

First of all, drop all the `routedIn` calls. These are meant only for when you want to use the same destination inside multiple NavGraphs. Doesn't seem like that is your case.

Then, the error is actually pretty clear. You have two things with the same route. If you open the generated `DashboardDestination` I'm guessing you'll see the route "dashboard" which clashes with the one you created here for the corresponding nav graph.
You can either rename the dashboard nav graph route or rename the Dashboard Composable to DashboardScreen (I usually call my screens  "SomethingScreen" which creates routes like "something_screen"). Usually, you wouldn't need to care about routes, but since you are manually creating your NavGraphs object, you need it.

**Comment by rezyfr** [comment]
"Usually, you wouldn't need to care about routes, but since you are manually creating your NavGraphs object, you need it."

I tried to not create my own NavGraphs, but it said Unresolved reference: NavGraphs when I called `NavGraphs.root` on my DestinationNavHost.
So I refer to [Tivi](https://github.com/raamcosta/tivi) Repository on how to setup the compose-destination, is there something I miss on my implementation?

**Comment by raamcosta** [comment]
Tivi is a special case because it uses Destinations on multiple Nav Graphs. It is fine, you can copy from there, but you can also remove the `routedIn` calls (like I said previously).

Also, In Tivi example, I don't have the same name in multiple routes :D 
Which again, as I explained before, you need to rename your Dashboard Destination Composable.

Other than that, no, you're not missing anything I don't think. It is looking good!
And yes at the moment, when having multiple modules, creating your NavGraphs object is the way to go.

**Comment by rezyfr** [comment]
Thanks Rafael, I just tested it with a little bit adjustment and all works like a charm ^^
