### ISSUE TITLE
detekt error `RedundantVisibilityModifierRule` in generated code

### ISSUE THREAD

**Issue by yogurtearl** [raamcosta/compose-destinations#327]
`compose-destinations` version: `1.7.30-beta`
`detekt` version: `1.22.0`

`compose-destinations`  `ksp` generates this code:

```kotlin
public class MyLabelsNavType
```

Which triggers this detekt warning:

```
RedundantVisibilityModifierRule: Line 16: MyLabelsNavType is explicitly marked as public. Public is the default visibility for classes. The public modifier is redundant.
```

See detekt docs: https://detekt.dev/docs/rules/style/#redundantvisibilitymodifierrule

No need to explicit specify `public` on classes or objects

**Workaround:**

Consumer of this lib can exclude generated sources in detekt config: https://detekt.dev/docs/introduction/configurations/#path-filters--excludes--includes

**Comment by raamcosta** [comment]
Hi @yogurtearl!

This was done for #221.

I don't think generated code should be subject to linters like detekt because:
- The generated code was not written by your team
- Your team shouldn't care about the generated code, it's not going to be maintained or read. So a lot of warnings don't actually matter
- Has code generated tool, there will always be conceptions done in the name of simplifying the code that generates the code. For example, instead of adding another config, another if to whether or not to use explicit api, I just do it always since there really is no harm in it.

Does this make sense to you?

**Comment by raamcosta** [comment]
I'm closing this for lack of feedback. Let me know if I can still help any further :)
