### ISSUE TITLE
How would one change the SoftInputMode for one particular screen

### ISSUE THREAD

**Issue by SiavashB** [raamcosta/compose-destinations#331]
Back when each screen had it's own fragment, in the screens where we wanted a particular type of input mode, we just called 
`activity?.window?.setSoftInputMode()`
But in a solution using Compose Destinations, we just have one central fragment so it's not clear how to do that, because it would be set for all screens. 
Is there a way to specify a SoftInputMode for one particular screen (aka Destination) using your lib? 

p.s I did think about sending an event back to the fragment using an EventFlow, but I was hoping there might be a cleaner solution. Like a parameter to the @Destination annotation. 

Or like a call back that gets called when the screen is changing, so that we can perform certain actions based on the screen. 

Thanks Ram

**Comment by raamcosta** [comment]
Hi @SiavashB !

> Or like a call back that gets called when the screen is changing, so that we can perform certain actions based on the screen.

That would probably work.
You can get current destination above the DestinationsNavHost call with something like:

```kotlin
NavController.currentDestinationAsState()

// OR

NavController.currentDestinationFlow()
```

Prefix above methods with "app" if you want to get a sealed `Destination` instead of `DestinationSpec`. (but these app* methods are generated).


Another way would be to have some kind of component which makes these actions and pass it down to the Screens with `dependenciesContainerBuilder`. Check it here https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters#use-dependenciescontainerbuilder-to-prepare-dependencies

If you do that, wrap this component in an interface, so that your screens are not tied to an Android specific class and you can pass a fake in tests.
