### ISSUE TITLE
Getting intent uri data in root destination's viewmodel

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#333]
In Activity I get the as part of bundle in intent.
Then from there I launch a screen, which is root destination.

```
@RootNavGraph(start = true)
@Destination
@Composable
fun Screen(
    navigator: DestinationsNavigator,
    vm: VM= hiltViewModel()
)
```

Here I want to get that intent data in `VM`
How can I get that in as part of `savedStateHandle` in `VM`

**Comment by raamcosta** [comment]
Hi @UKMIITB !

I would simply pass it as non-navigation argument.
Check both ways to do it here:

https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters

Or, using the manual composable alternative, you can get a hold of your hiltViewModel() and call some setter method directly there instead of passing it to the Screen composable.
Something like:

```kotlin

DestinationsNavHost(
    navGraph = NavGraphs.root
) {
    composable(SomeScreenDestination) { //this: DestinationScope<SomeScreenDestination.NavArgs>
        val vm = hiltViewModel<YourViewModelName>()
        vm.setData([YOUR DATA])
        
        SomeScreen(
            navigator = destinationsNavigator, // destinationsNavigator is a `DestinationsNavigator` (also lazily evaluated)
        )
    }
}
```
