### ISSUE TITLE
Deeplink synthetic backstack

### ISSUE THREAD

**Issue by cvb941** [raamcosta/compose-destinations#334]
Hello,

When opening an app using a deep link, navigating back closes the application, since there are no screens in the backstack. You could use `navigate` with the `singleTop` option, which works only when there is only one possible parent screen.

The classic navigation library [seems to create](https://developer.android.com/guide/navigation/navigation-deep-link#handle) a synthetic backstack automatically based on the graph XML resource.

Do you have any tips on how to achieve proper back navigation from deeplinks using the compose navigation library, and of course, compose destinations? Some kind of way to define a backstack next to deeplinks? Thanks.

**Comment by raamcosta** [comment]
Hi @cvb941 !

I don't actually know how to do this. It's not the place of compose destinations to do it either. But I am curious if you find a way to do it with official compose navigation, because I wanna make sure we support that here too.

So let me know if you find that 🙂 

For now, I'll close since I don't think this is in the scope of the library.
