### ISSUE TITLE
Integrate DestinationNavigator and NavResult.

### ISSUE THREAD

**Issue by dylan-kwon** [raamcosta/compose-destinations#374]
How about integrating the `NavResult` function, which is currently separated into `DestinationsNavigator`, `ResultRecipient` and `ResultBackNavigator` into `DestinationsNavigator`?

For example like this code:

```kotlin
navigator.navigateUp(result)
navigator.popBackStack(result)
```

```kotlin
navigator.onNavResult<Destination> { result ->
    when(result) {
        is NavResult.Value -> {
            // Value..
        }
        is NavResult.Canceled -> {
            // Canceled..
        }
    }
}
```

**Comment by raamcosta** [comment]
This won't work because the ResultBack navigators/result recipients are typed and these types are checked at compile time to ensure proper type-safety.

So the library needs a parameter on the Composable Destinations that will both send results and receive them with these type arguments.

Closing this, but please let me know if you have further suggestions!
