### ISSUE TITLE
DestinationsNavigator navigation while resumed cannot pop a single level easily

### ISSUE THREAD

**Issue by mattinger** [raamcosta/compose-destinations#382]
The existing DestinationsNavigator has some functions for navigating only if resumed.  However, the functionality to supply a pop up along with that is not easy to use in a generic fashion to do things like pop up a single level.

For example, the following seems to be the only way to navigate to a destination after popping a single level, and requires both the DestinationsNavigator as well as the underlying NavController.

```
    navigator.navigate(MyDestination, true) {
        navController.previousBackStackEntry?.destination?.route?.let { previous ->
            popUpTo(previous) {
                inclusive  = false
            }
        }
    }
```

You cannot make this two calls because as soon as you call "popBackStack" on the navigator, the current destination won't ever be resumed and the second part of the navigation can't happen:

```
navigator.popBackStack()
navigator.navigate(MyDestination, true)
```

I'd really love a way to ask the DestinationsNavigator itself what it's previous destination stack looks like, so i can pop up a single level at a time, without having to know the exact destination we're popping up to.

**Comment by raamcosta** [comment]
Hey @mattinger !

So you are popping up to last screen in the back stack but not "inclusively" (see `inclusive = false`). If that is the case, why don't you just pop the current one inclusively?

```kotlin
    navigator.navigate(MyDestination, true) {
            popUpTo(CurrentDestinationYoureDoingThisFrom) {
                inclusive  = true
            }
    }
```

**Comment by mattinger** [comment]
I think this would solve this one particular use case, the there are other cases where you might want to pop back more than just a single screen.  For use, we also have a use case that requires us to clear the entire stack and start over from the root destination (which is actually not on the navigation stack since it's a loader screen that pops itself off before it navigates to the welcome screen).  I think just having some useful access to the backstack from the navigator would be helpful if it's at all possible.

**Comment by raamcosta** [comment]
To have the whole back stack info is not possible because it’s also not possible when using NavController and the jetpack compose navigation APIs. (There are some restricted APIs that I sometimes use to log the back stack, but I definitely don’t feel comfortable recommending these APIs for any serious work since they are restricted and we shouldn’t use them as they can just delete these APIs or change them anytime. If you really wanted to use these APIs you could, just use NavController instead of DestinationsNavigator and you’d be able to do it. But don’t do it, it’s not a good idea.)

That said, I feel like there is a reason why official APIs don’t provide this and the fact that this “limitation” didn’t present a problem for so long (note that the same is true for fragment navigation) must mean that it is not needed. I don’t know if I’m missing any use case where it would be needed, if so let me know. 

For the case that you want to pop all backstack and navigate to the start destination, it’s also fairly trivial to do. There is always (with Compose Destinations) an entry in the back stack related with the NavGraph you pass to DestinationsNavHost. So you can pop up to that (inclusive false) and navigate to the start destination, similar to what we did above.

**Comment by raamcosta** [comment]
@mattinger let me know if there's anything else I can do!

I'll close this one for now. If you believe this to be a real limitation, my recommendation is to open an issue for compose navigation (since this is where the limitation comes from).
