### ISSUE TITLE
DestinationsNavHost startRoute with arg 

### ISSUE THREAD

**Issue by miduch** [raamcosta/compose-destinations#384]
Would it be possible to have DestinationsNavHost with also accepts String as startRoute? Or allowing in some other way to pass dynamically/fully constructed start route string as startRoute: Route? 

```
@Composable
fun DestinationsNavHost(
    navGraph: NavGraphSpec,
    modifier: Modifier = Modifier,
    startRoute: Route = navGraph.startRoute,
    engine: NavHostEngine = rememberNavHostEngine(),
    navController: NavHostController = engine.rememberNavController(),
    dependenciesContainerBuilder: @Composable DependenciesContainerBuilder<*>.() -> Unit = {},
    manualComposableCallsBuilder: ManualComposableCallsBuilder.() -> Unit = {}
) {
    HandleNavGraphRegistry(navGraph, navController)

    engine.NavHost(
        modifier = modifier,
        route = navGraph.route,   < ----- this is string 
        startRoute = startRoute,
        navController = navController,
    ) {
        addNavGraphDestinations(
```

**Comment by raamcosta** [comment]
Hey @miduch 

What is the use case? I can't think of a reason to do this.. are you trying to pass nav arguments to the first screen?

**Comment by miduch** [comment]
> Hey @miduch 
> 
> are you trying to pass nav arguments to the first screen?

Yes exactly

**Comment by raamcosta** [comment]
That's not possible, not even with the official compose navigation library. The route you pass here is the one with placeholders instead of "real arguments".

If you want to pass "stuff" to the first screen from the place you call DestinationsNavHost, you can use one of these methods:

https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters

**Comment by raamcosta** [comment]
Hoping that helped! Let me know.
