### ISSUE TITLE
How can i use inclusive option?

### ISSUE THREAD

**Issue by leejooheon** [raamcosta/compose-destinations#42]
This is the code that sets the Splash screen as the starting point and goes to the Home screen after 2 seconds.
When press BackKey on the Home screen, it goes back to the Splash screen.

```kotlin
@Destination(start = true)
@Composable
fun SplashScreen(
    navigator: DestinationsNavigator
) {
    Column(modifier = Modifier.fillMaxSize()) {
        Text(text = "splash screen")
    }
    delay(2000L)
    navigator.navigate(HomeScreenDestination())
}
```

```kotlin
@Destination
@Composable
fun HomeScreen(
    navigator: DestinationsNavigator
) {
    Column(modifier = Modifier.fillMaxSize()) {
        Text(text = "home screen")
    }
}
```

Is there any way to prevent this happening?
Thanks.

**Comment by raamcosta** [comment]
Hi @leejooheon !

Yes it works exactly the same way 🙂
You can check the DestinationsNavigator.navigate method and you'll see that It also accepts the same parameters that NavController does.

Also keep in mind that you can use NavController directly instead of DestinationsNavigator.

Let me know if you could make that work. I'm not on the PC at the moment so I can't paste a snippet here now but I can do so later if it will help!

**Comment by raamcosta** [comment]
You should be able to.

When navigating away from the SplashScreen do this:

```kotlin
destinationsNavigator.navigate(HomeScreenDestination) {
    popUpTo(SplashScreenDestination.route) {
        inclusive = true
    }
}
```

**Comment by leejooheon** [comment]
Thanks a lot!! it works perpectly!!
