### ISSUE TITLE
Destination.baseRoute marked as protected but needed

### ISSUE THREAD

**Issue by Nek-12** [raamcosta/compose-destinations#421]
The base route is now marked protected

```
  @get:RestrictTo(RestrictTo.Scope.SUBCLASSES)
    val baseRoute: String
```

Is there a particular reason for that? 
Currently, we're using `baseRoute` for some deeplink building and analytics in our app.

**Comment by raamcosta** [comment]
Well basically the main idea is to not have people using that instead of route. There are few cases where you need to use route and even less where you need baseRoute.

But it’s just a warning, feel free to ignore it 🙂

For analytics we could start implementing toString method. And for deep links, can’t you just use the normal route?
A good thing you can do to create deep links is to call it’s invoke function as you would when navigating to it, then use the resulting Direction’s route which will be a route with resolved arguments.

**Comment by Nek-12** [comment]
Thanks for the answer. Yes, a toString method would be perfect - it would prevent people from misusing the baseRoute, but leave space for logging / analytics / etc. 

It's a warning but the compiler marks is as an error, just does not prevent compilation. I think that's too much. Maybe you could use something like a custom experimental-like annotation. 

We have a set of "special" deeplinks which we detect by their destination's baseRoute. Is that not correct?

**Comment by Nek-12** [comment]
By the way, instead of implementing toString you could mark destinations as `data object`s. We'll have to migrate our reports to the new name but it's a good change overall.

**Comment by raamcosta** [comment]
No longer marked as protected.
