### ISSUE TITLE
Removing NavArgs after navigation

### ISSUE THREAD

**Issue by Berthod** [raamcosta/compose-destinations#427]
Is there a way to remove NavArgs? I need to pass data between BottomBar Destinations, which works fine. The problem is that the args persist everything and every time I navigate to the destination, the args get applied again.

In Compose Navigation you would typically do something like this
`backStackEntry.savedStateHandle.remove<String>("key")` 
but it has no effect when using compose-destinations and the args are still kept.

I take args like this 

```
data class NavArgs(
    var key: String? = null
)
```

```
@Destination(
    navArgsDelegate = NavArgs::class
)
@Composable
internal fun Route(

```
`val args = RouteDestination.argsFrom(backStackEntry)`

make actions based on the result in LaunchedEffect
```
LaunchedEffect(Unit) {
  args.key?.let {
  ...
  backStackEntry.savedStateHandle.remove<String>("key") //does not remove the arg
  }
}
```
and navigate like this

```
navigator.navigate(
  RouteDestination(NavArgs("args"))
) {
    popUpTo(RouteDestination.route)
    launchSingleTop = true
}
```

**Comment by raamcosta** [comment]
Hi!

I find this usage very weird and unnatural and I never saw a real case where I needed to use it.
That said, I don't see a reason for removing the arg to not work, we are using the SavedStateHandle in the expected way. 

Can you prepare a sample app where you reproduce this issue so I can take a deeper look? Thanks

**Comment by raamcosta** [comment]
I'll close this for being stale. Let me know if there's any additional feedback!

**Comment by komar-tgm** [comment]
Hi, I would like to extend that question:
I navigate from Screen A to to Screen B with navArgs (contains a Boolean value to trigger a Snackbar). Now I can navigate to Screen C. If I return from Screen C to Screen B, I pass a value via ResultBackNavigator navigateBack, or just navigate with navigator.popBackStack() (there are 2 different ways). The problem is that both different approaches encounter the same problem: The navArgs that triggered true in the first place is still true (default value is set to false). How can I popBack or navigateBack and have the navArgs at it's default value again?
Thanks

**Comment by raamcosta** [comment]
I think passing a nav argument just to trigger a one time thing on the new screen is not something I would do 🤔
That said, it’s probably not so easy to do with compose destinations since this was never thought of as a use case, but if you open the generated destination you can see how we are getting the nav arg from the SavedStateHandle and you can probably figure out how to change that value or remove it 🙂
