### ISSUE TITLE
[Feature request] Custom navigation argument as StateFlow

### ISSUE THREAD

**Issue by ammargitham** [raamcosta/compose-destinations#435]
Currently, if we provide a navigation argument of non primitive type (for eg. `@Serializable`) and try to access the `StateFlow` (using `asStateFlow()`) from the `savedStateHandle`, the return type is a `ByteArray`. This is internally handled in `savedStateHandle.navArgs()`, but there is no function to return the value as a flow.

Currently the only way seems to be to manually map the returned `StateFlow<ByteArray>`, convert the `ByteArray` to the actual type using `DefaultKtxSerializableNavTypeSerializer`.

This is what I am doing currently:
```kotlin
private val searchFlow: Flow<Search?> = savedStateHandle.getStateFlow<ByteArray?>(
    "search",
    null
).mapLatest {
    it?.run {
        DefaultKtxSerializableNavTypeSerializer(Search.serializer()).fromByteArray(it)
    }
}
```

It would be great if a helper extension function is generated for this.

**Comment by raamcosta** [comment]
Hi! 👋 

Navigation arguments should be static. They shouldn't change while you are on a screen.
They represent values that were sent from the previous screen, this happens in the past so even if you can change them, I wouldn't recommend it since it will be confusing for other maintainers to think of "navigation arguments" and then keep in mind also that they can change over time.

Whatever you're trying to do, I would just initialize the state with the navigation arguments and then change it (if you still want to do saved them across process death, you can still use the SavedStateHandle, just using another key for it).
