### ISSUE TITLE
Set arguments to start destination

### ISSUE THREAD

**Issue by andrewafanasenko** [raamcosta/compose-destinations#436]
Hello, have one question about start destination arguments: suppose I have some activity that has setContent {} method with defining of nav host
```
val args = intent.extras?.getParcelable<LogInArgs>(EXTRA_LOGIN_ARGS)

override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    
    // How I can pass `args` to LogInDestination???
    
    setContent { 
      DestinationsNavHost(
        navGraph = NavGraphs.root,
        navController = rememberAnimatedNavController()
      )
    }
}
```

The first destination looks like:

```
@RootNavGraph(true)
@Destination(
    navArgsDelegate = LogInArgs::class
)
@Composable
fun LogInDestination(
  navController: DestinationsNavigator
) {
....
}
```
So, I want to set `LogInArgs` to first destination when opening activity (from extras) and get them in the destination's view model ( `val navArgs: LogInArgs = savedStateHandle.navArgs()`).
Is it any way to do this? 

Not sure if the following implementation will call `viewModel.setArgs(navArgs)` every time recomposition happening (I need args setting only once, like in `init` method of view model)

```
@RootNavGraph(true)
@Destination()
@Composable
fun LogInDestination(
  navController: DestinationsNavigator,
  navArgs: LogInArgs
) {
 val viewModel = hiltViewModel<LogInViewModel>()
 viewModel.setArgs(navArgs)
}
```
Thank you

Update: I have checked the last approach with sending arguments to the start destination in `dependecy(navArgs)` and taking it directly in the composable function. Result: `viewModel.setArgs(navArgs)` is called every time I return back from other destinations to root one.

**Comment by raamcosta** [comment]
Hi!

Start destinations do not have navigation arguments. However, you can pass whatever you need from the place where you call DestinationsNavHost.

> Update: I have checked the last approach with sending arguments to the start destination in dependecy(navArgs) and taking it directly in the composable function. Result: viewModel.setArgs(navArgs) is called every time I return back from other destinations to root one.

You can pass the arguments as you create the ViewModel with assisted injection. If it's too complicated to do with Hilt, then just check in your VM if the args were already set, if so ignore subsequent calls.

Also put that code in a LaunchedEffect so that it doesn't happen on all recompositions:

```
LaunchedEffect(viewModel) {
    viewModel.setArgs(navArgs)
}
```

Also, do not call this parameter "navArgs" that is misleading. These are not navigation arguments, it is just something yo'r passing from top level.

**Comment by raamcosta** [comment]
Let me know if this helps!
