### ISSUE TITLE
Question: Share ViewModel with navigation arguments

### ISSUE THREAD

**Issue by chriswiesner** [raamcosta/compose-destinations#438]
Hi,

I want to share a ViewModel across 3 screens and the VM relies on navigation arguments (passed through the first screen).

When using the `dependenciesContainerBuilder ` to share across screens i do not have the ability to use navArgs out of the box.
Can I "inject" those arguments somehow?

**Comment by raamcosta** [comment]
Hi @chriswiesner 

`dependencyContainerBuilder` lambda does have access to current nav args through a field named `navArgs`.

Unless I missunderstood your question.

**Comment by chriswiesner** [comment]
oh thanks,

i'm still not quite sure how i would pass the navArgs to the savedStateHandle then.

```
dependenciesContainerBuilder = {
    ...
    dependency(hiltViewModel<MyViewModel>(sharedLifeCycleOwner)) {
        // call custom constructor setting navArgs in savedStateHandle?
        // or use hiltViewModel delegate and just ".apply" the args to the savedStateHandle?
    }
}
```

**Comment by raamcosta** [comment]
You shouldn't need to do that? 🤔 

You can just call SavedStateHandle.argsFrom method and they should provide you with the arguments you want.
If this is not the case, please provide me a small repository that I can deep dive and find what I can do to help in this scenario! 🙏

**Comment by chriswiesner** [comment]
i've uploaded a sample here: https://github.com/chriswiesner/SharedNavArgs

i think you are referring to manual creation of the VM - i was still in the assumption i could use hilt

**Comment by chriswiesner** [comment]
problem is that the ViewModel is relying on navArgs which are propagated by a destination in the graph.
so i cannot provide the VM in the graph as dependency{} from the start.
i need to lazily instantiate the ViewModel once I navigate to the first destination that requires it.

**Comment by raamcosta** [comment]
Hi @chriswiesner 

Sorry, it took me a while.

```kotlin
                    DestinationsNavHost(
                        navGraph = NavGraphs.root,
                        dependenciesContainerBuilder = {
                            dependency(hiltViewModel<SharedViewModel>(this@MainActivity))
                        }
                    )
```

This will tie your ViewModel to the Activity. The activity will is never going to have the navigation arguments so the ViewModel's SavedStateHandle won't either.
Assuming you want to share the instance of the ViewModel with yout two screens, and since you cannot tie it to your activity, the best option is to create a nested nav graph and tie your ViewModel to it.

I made the changes and got it working here:
https://github.com/raamcosta/SharedNavArgs/commit/c57d6f1f2fee83f79ff8bc6ecf1f313fb518b24a

NOTICE that for now (until v2 of this library) start destinations of NavGraphs cannot have mandatory arguments and this is why I had to make the "id" parameter null and then assert that it isn't null in the ViewModel.
Even though it's not ideal, with official compose navigation you would always have to assert it in similar way.
After v2, we will be able to define mandatory arguments for start destinations of nested graphs, so you will be able to remove the "?" nullable sign from NavArgs class.

**Comment by chriswiesner** [comment]
Thank you for taking the time!
I'm looking forwarding to v2 🚀
