### ISSUE TITLE
Inquiry about updating navigation-compose to version 2.7.0

### ISSUE THREAD

**Issue by KangYee** [raamcosta/compose-destinations#448]
Hi,

I wanted to inquire about the possibility of updating navigation-compose to version 2.7.0. I noticed in the release notes that AnimatedContent has become Stable and Accompanist Navigation Animation will be deprecated soon.

Here is the link to the release notes: https://developer.android.com/jetpack/androidx/releases/navigation#2.7.0-alpha01

Could you please let me know if there are any plans to update navigation-compose to version 2.7.0?

Thank you.

**Comment by raamcosta** [comment]
Hi!

Yes, of course. I am definitely aware of this and I was planning to not use accompanist under the hood only from v2 onwards. I can revisit this if I see enough interest, but since v2 is being actively worked on and I'm hoping to release it soon, I was tempted to avoid myself this additional change for 1.9.x.
Let me know what you think about this though.. V2 could still be a couple of months away and there will be more API changes, so adopting v2 might be more than just bumping the version (although it shouldn't be super complicated, and I plan to document all changes and migrations needed of course).

**Comment by KangYee** [comment]
Waiting for version 2.7.0 to stabilize before considering an update is a good idea. Thank you for your prompt response.
