### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by obvionaoe** [raamcosta/compose-destinations#449]
Currently there are a lot of deprecated things that have no mention in the documentation.

It should be made clear how to replace the deprecated calls for the new ones.

Thanks for your work so far

**Comment by raamcosta** [comment]
Hey @obvionaoe 👋

Yeah you’re definitely right, I am sorry I am trying my best to do it but so far it has been to much for just one person. 😅

Btw if you notice something while checking the documentation, there’s a “edit this page” button at the bottom where you can very easily update the markdown file correspondent and open a PR.
This is not me escaping this request or anything, it’s just that I would appreciate and be really thankful 🙏

Another reason I’ve been less active there is that I am focused on changes for version 2 which will come with its own documentation (website will have versioning and user can choose, v2 docs will be changed from v1 but both will exist at the same time since I plan to maintain both versions for quite some time).

**Comment by obvionaoe** [comment]
Hi! I'd love to help but I don't think I have a deep enough understanding of the library to be able to provide documentation :/

**Comment by raamcosta** [comment]
Hi @obvionaoe 

Of course, that’s totally fair 🙂

Let me know what deprecated APIs you found in documentation with no mention. I’ll be sure to spend some time updating it.

**Comment by Nek-12** [comment]
Actually I want to chime in. Some of the features you made were never documented. Like wrappers or custom destination annotations. I think we should mention them in the docs

**Comment by raamcosta** [comment]
Also totally fair, I know that’s the case 😅

With v2 coming up, I’ll go through the documentation updating and adding everything.

Life and work have kept me very busy lately, but rest assured I am still very invested in this. V2 is also keeping me busy.

**Comment by cgudea** [comment]
To be honest, the edit option was so well blended into the page I didnt even realize I could submit changes!

It may make sense to change the call to action from "**Edit this page**" to something more eye catching or obvious. Maybe something like:

"**Found a mistake? Information lacking? Edit or expand this page**"

Either way, going forward I will personally be keeping an eye out for documentation issues and try to contribute when and where I can. This library is great and I have wanted to give back in some way. Thanks for you hard work @raamcosta!

**Comment by raamcosta** [comment]
This is better now with v2 docs! I'll close this, thanks guys!
