### ISSUE TITLE
Error when Setting StartRoute to Child NavGraph

### ISSUE THREAD

**Issue by hscissors** [raamcosta/compose-destinations#450]
We have a situation in an app that has multiple sub-graphs  (but one module).

When the app starts, there are times when we want the start destination be different than the default `NavGraphs.startRoute`. However, if we change the `startRoute` to a the start route of a different child graph, the Android X library complains about it not being in the graph.

In we have something like:
```
@RootNavGraph(start = true)
@NavGraph
annotation class UnauthenticatedNavGraph(
    val start: Boolean = false
)

@RootNavGraph
@NavGraph
annotation class AuthenticatedNavGraph(
    val start: Boolean = false
)


@AuthenticatedNavGraph(start = true)
@NavGraph
annotation class BottomNavGraph(
    val start: Boolean = false
)

...

@BottomNavGraph(start = true)
@Destination
@Composable
fun SomeScreen( ... )
```

And we trying a do this: 

```
DestinationsNavHost(
      navController = navHostController,
      engine = rememberAnimatedNavHostEngine(
          navHostContentAlignment = Alignment.TopCenter,
          rootDefaultAnimations = RootNavGraphDefaultAnimations.ACCOMPANIST_FADING
      ),
      navGraph = NavGraphs.root,
      startRoute = if(authenticated) NavGraphs.authenticated.startRoute else NavGraphs.unauthenticated.startRoute
  )
```

The app crashes with the following error when authenticated == true:

```
FATAL EXCEPTION: main
Process: com.doximity.amiondroid.v2, PID: 15933
java.lang.IllegalArgumentException: navigation destination bottom is not a direct child of this NavGraph
	at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.kt:81)
	at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.kt:58)
	at androidx.navigation.NavController.navigateInternal(NavController.kt:265)

```

**Comment by raamcosta** [comment]
Which is true right? Bottom is not a direct child of the NavGraph you’re passing to the DestinationsNavHost. It’s a child of the child.

So, instead of passing NavGraphs.authenticated.startRoute, just pass NavGraphs.authenticated and that should work and also produce the same result you’re looking for.

**Comment by hscissors** [comment]
That works for this situation, but let's stay you had a bottom navigation with 4 destinations and you wanted to restore the user to the last one they were on, when they start the app. We'd need to change the start to `NavGraphs.authenticated.bottom.Desintation1` or `NavGraphs.authenticated.bottom.Desintation2`. How would that work?

**Comment by raamcosta** [comment]
Just to be clear, this is not a limitation imposed by this library, it is coming from the official navigation library.

I believe in that case either it’s a case that the app would automatically restore the user deeper in the graph or you can manually navigate to it in a LaunchedEffect (which might be slightly noticeable I guess 🤔).
But otherwise yes, it seems like if you’re defining a graph on NavHost then the start destination must be a direct child graph or destination.

**Comment by hscissors** [comment]
Would it make sense to use deep links in this situation, or a `LauncheEffect` with a direct call to navigator?

**Comment by raamcosta** [comment]
I believe you don’t necessarily need deep links.. 🤔 I would start with normal navigate call inside some side effect compose api, personally 🙂

**Comment by raamcosta** [comment]
Closing the issue, hoping that was helpful @hscissors !
