### ISSUE TITLE
Passing destination which needs parameter to startRoute

### ISSUE THREAD

**Issue by UKMIITB** [raamcosta/compose-destinations#456]
@raamcosta 
In case if I have a destination which needs some parameter, then I am unable to convert those to Route type.
Can you please help on this
I want to dynamically pass startRoute

**Comment by raamcosta** [comment]
This is not possible and it is NOT a limitation of this lib. Official compose navigation also won’t let you pass nav arguments to the start screen.

If this screen is your start screen, then navigation arguments don’t make sense since those are meant for when you’re navigating fromscreen to screen. Instead, you can pass that data via these two ways:

https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters

**Comment by raamcosta** [comment]
I'm closing this after above explanation. Let me know if all is understood! :)
