### ISSUE TITLE
 I really want your opinion

### ISSUE THREAD

**Issue by aplha98** [raamcosta/compose-destinations#489]
I read your medium article "considering-all-unhappy-paths", I really want your opinion about making something like this
```
data class AllMagicCardUseCaseError(
    val apiCallError: ApiCallError?,
    val dateBaseCallError: DateBaseCallError?,
    val networkFailure: GetMagicCardUseCaseError?,
) : UseCaseError
```
instead of keep adding class to ApiCallError
 sealed interface ApiCallError : GetSomethingUseCaseError, UpdateSomethingUseCaseError, CreateNewDeckError

**Comment by raamcosta** [comment]
I don’t like it because you’ll never have more than one of those errors.

instead, you could do

```Kotlin
sealed interface MyUseCaseError {
    data object MyErrorType1 : MyUseCaseError
    data object MyErrorType2 : MyUseCaseError
    data class RemoteError(val error: ApiCallError) : MyUseCaseError
}
```

So instead of changing the ApiCallError sealed, you have another class wrapping it here.
Not as convenient for dealing with errors as my suggestion in th article but it solves the issue with multiple modules for example.
