### ISSUE TITLE
Pass parameters that could change over time

### ISSUE THREAD

**Issue by mrzbn** [raamcosta/compose-destinations#494]
in the sample of passing parameters, when passing ScaffoldState, even if ScaffoldState changes in scaffold, in the destination, the instance that is passed, will not change.

**Comment by raamcosta** [comment]
Hi!

Check this area from docs:
https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters

Namelly this:

> [1. Manually call your screen Composable, which is made super easy by the library](https://composedestinations.rafaelcosta.xyz/destination-arguments/navhost-level-parameters/#manually-call-your-screen-composable)
This is the preferred way if you want to send something that is tied to Compose runtime (f.ex a State<Something>). The other approach uses a Map<Class<[Component]>, [Component]> so if Component changes your screen won't be recomposed. Also, it is a bit type safer since you are the one calling the Composable function.

I'm assuming you are using dependency container, but that is not meant for something that is tied to a Compose state since that just holds classes, it doesn't know about Compose state. So try calling your Composable manually instead if you really need to pass something like this :)

**Comment by raamcosta** [comment]
I'll close this since I think it is answered, but let me know if I can help any further!
