### ISSUE TITLE
Handling App links

### ISSUE THREAD

**Issue by javokhirsavriev** [raamcosta/compose-destinations#495]
Does the library support [App Links](https://developer.android.com/training/app-links)?

These are how i'm using it now

``` xml

<intent-filter>
    <action android:name="android.intent.action.VIEW" />

    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />

    <data android:scheme="uz.uzinfocom.myid" />
</intent-filter>

<intent-filter android:autoVerify="true">
    <action android:name="android.intent.action.VIEW" />

    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />

    <data
        android:host="myid.uz"
        android:pathPattern="/api/v.*/oauth2/authorization"
        android:scheme="https" />
</intent-filter>
```

``` kotlin

@Destination(
    deepLinks = [
        DeepLink(
            uriPattern = "https://myid.uz/$FULL_ROUTE_PLACEHOLDER"
        )
    ]
)
@Composable
fun AppLinkScreen() {
}
```

But it doesn't work. I logged the data from the intent through the ```onNewIntent()``` method and got this result.

```
uz.uzinfocom.myid://authorization?client_id=test&auth_method=simple&status=0&state=None&method=simple&scope=address,contacts,doc_data,common_data
```

Clicked url

```
https://myid.uz/api/v1/oauth2/authorization?client_id=test&response_type=code&scope=address%2Ccontacts%2Cdoc_data%2Ccommon_data&method=simple
```

But I can't navigate the required screen.

Please help.

**Comment by raamcosta** [comment]
All I did related to deep linking was exposing the same APIs we have with official compose navigation with our annotations.

If this is possible with official library than it should be possible with compose destinations because the APIs are one to one. But I don’t know much past this , sorry 😬

My suggestion is try googling or asking on Kotlin slack about this from the perspective of the official compose navigation library, then it should be fairly simple to use the solution with compose destinations.
