### ISSUE TITLE
Multi-modular usage of library, documentation lacking information

### ISSUE THREAD

**Issue by Cuyer** [raamcosta/compose-destinations#507]
Hi, can someone help me understand what routedIn() function does? As we have to create NavGraph ourselves if we have multi modular project and in NavGraphs object we have to declare our NavGraphs I suppose.

Let's say I have 3 functionalities, Authentication, Searching and Dashboard. For each of them I have to create object that then is assigned to the root.

1. What does routedIn() function give me? It is often added before associateBy() and in startRoute

2. What is listOf<DestinationSpec<*> used for? Is it some kind of NestedNavGraph?

3. Why in Tivi repository each object has multiple destinationsByRoute DestinationSpecs?

4. We have to create root for our NavGraph, can I create more of "roots"? If so, in what use cases I could do that?

Im reaching here for help as I find documentation for multi modular projects quite lacking information.

In my NavGraphs object I have currently following code:

```
val dashboard = object : NavGraphSpec {
        override val destinationsByRoute: Map<String, DestinationSpec<*>>
            get() = listOf<DestinationSpec<*>>(
                DashboardScreenDestination
            ).associateBy { it.route }
        override val route: String
            get() = "dashboard"
        override val startRoute: Route
            get() = DashboardScreenDestination

    }
```

**Comment by raamcosta** [comment]
Hi @Cuyer !

Thank you for opening the issue!

So.. `routedIn` is a function created only for the rare cases where you want to dynamically make a destination part of multiple NavGraphs. When I forked tivi project, it used a specific multi modular navigation structure where each module exposed a single screen. Each of these screens belonged to multiple NavGraphs. Since KSP operates on a "per-module" basis the only way to have these screens (or in our case, generated Destinations) part of multiple NavGraphs is if we do it at runtime.
Since each destination must have a unique route, `routedIn` basically creates a new Destination at runtime which is exactly like the original except it has a different route (ex: "profile_screen" becomes "some_graph/profile_screen"). The even more annoying part is that if you do that, when navigating you need to specify which of these "dynamic destinations" you want to navigate to, and to do that you have to do something like `navController.navigate(Destination(args) withIn NavGraph)`. `navController.navigate(Destination(args))` is a totally valid call in terms of static typing safety, so it will let you do that but it will crash at runtime since Destination (the original one) isn't actually part of your graph, only the clones you did with `routedIn` are.

Usually, for most apps, I would say that what you want is for each feature module to expose a full NavGraph and probably you don't want to have screens belonging to multiple NavGraphs. In this scenario (you can look at the CaloriesTracker example) you don't need the `routedIn` calls (in fact you shouldn't use them).

I do regret it a little bit to have created this API for this very narrow use case (that can probably be solved in a different way anyway) and I also regret making tivi one of the examples. Multi-module support was added by looking at existing open source projects that had different approaches and trying to see how Compose Destinations could support them.

The reason it is not very well documented is that I have always felt that the current solution is not ideal in the sense that the developer experience of using Compose Destinations is much worse when using multi modules compared to when using a single navigation module. You can totally do it (and if you follow CaloriesTracker I think you'll have a better time) and you won't have issues with it per se, but the safety and experience is not great.
This is where v2 comes into play though. I've been coding for a while now to improve multi-module experience (and some other stuff) and I totally believe it will be much better on v2. At that point, I will definitely take more time to document the process better 🙂

**Comment by Cuyer** [comment]
I see that CaloriesTracker implementation is much cleaner. Exposing generated NavGraphs seems like better idea and is far more understandable than Tivi example. Thank you for the response!

**Comment by raamcosta** [comment]
Glad I could help!

closing this, but let me know if there’s anything else I can help with!
