### ISSUE TITLE
Background is shown on exit transition

### ISSUE THREAD

**Issue by Rawa** [raamcosta/compose-destinations#537]
Hello!

I've been trying to produce where 2 screens (Greeting & Profile) interact. Greeting is fixed, and the Profile slides in from the right on top of Greeting, when exiting I expect Profile to slide off to the right, (normal slide in right). I expect Greeting to show until Profile covers it by sliding over it.

The issue I have is when Profile is sliding in from the right, Greeting immediately gets removed and background is shown. If I set an animation like fadeOut as exitAnimation on Greeting, it will show the entire animation and keep the Greeting screen as long as the animation is running.

I've also set the animation style on the Greeting screen in this fashion:
```@Destination(style = DestinationStyle.Animated.None::class)```

Video showing the issue:
https://github.com/raamcosta/compose-destinations/assets/1526920/00c961a3-15d4-44d7-89ab-1226cdaa49bb
A patch that reproduces shown the issue on the playground:
[exit_animation_diff.patch](https://github.com/raamcosta/compose-destinations/files/13278867/exit_animation_diff.patch)

**Comment by raamcosta** [comment]
This is part of our playground app which is not meant as an example for anyone, it’s just where I do crazy things to test stuff.

As such, I don’t doubt there is plenty wrong things in it. What I can say is that animations on compose destinations are just a wrapper of the official APIs, such that we just provide a different way for users to tell the framework what animations they want and then we provide those when calling the official APIs.
Because of this, I’m sure we can either fix my implementation of this animation, or, if there is indeed some issue, it will most likely be with official library and not compose destinations.

let me know if this helps 🙂

**Comment by Rawa** [comment]
Thanks for your quick reply! I just dug deeper into it, it seems like it same issue appears on the standard library.
