### ISSUE TITLE
Bottom bar navigation documention that says to do `currentDestination == destination.direction` in selected doesn't select the element

### ISSUE THREAD

**Issue by dave08** [raamcosta/compose-destinations#553]
It seems like they don't match for some reason, even though the navigation to each page works.

**Comment by raamcosta** [comment]
Hi 👋 

> It doesn't seem like direction exists on the DirectionDestinationSpec...

can you elaborate on this? I don’t see what you mean…

`Route` still requires navigation arguments for it to become a `Direction` you can navigate to. So Direction is typically what you’d use here since when user clicks in the top level button to go somewhere, you don’t have any new data to pass in. Even if some of your nav bar destinations require arguments, they will be fixed and always the same, so when creating the enum (like in the docs) you can pass those in to get that Direction (although in that case you wanna make it a Direction and not a DirectionDestinationSpec).

**Comment by dave08** [comment]
This code seems to work (but not the version in the docs...):

```kotlin
        val navBackStackEntry by navController.currentBackStackEntryAsState()
        val currentDestination = navBackStackEntry?.destination

        NavigationBarDestination.entries.forEach { destination ->
            NavigationBarItem(
                selected = currentDestination?.route == destination.direction.route,
```

**Comment by raamcosta** [comment]
@dave08 was not using `DestinationsNavHost` so `currentDestinationFlow` wasn't working.

I'll make this usage throw a helpful exception so it is clear that that is a requirement.

**Comment by mattlewer** [comment]
I also had this problem, the docs show to do this (gave error One type argument expected for annotation class Destination<T : Annotation>):
```
    val currentDestination: Destination = navController.currentDestinationAsState().value
        ?: NavGraphs.root.startDestination    
```

The sample project code says to do this (all tabs say false):
```
val isCurrentDestOnBackStack = navController.isRouteOnBackStack(destination.direction)
```

What worked for me was Dave08's method:
```
        val navBackStackEntry by navController.currentBackStackEntryAsState()
        val currentDestination = navBackStackEntry?.destination
        NavigationBarDestination.entries.forEach { destination ->
            val isCurrentDestOnBackStack = currentDestination?.route == destination.direction.route
```
