### ISSUE TITLE
Bottom Sheet Bug

### ISSUE THREAD

**Issue by ghasemdev** [raamcosta/compose-destinations#57]
Hi, when I click the back button, the bottom sheet will be closed Immediately without any animation. 

https://user-images.githubusercontent.com/65798992/153896851-673d48f4-160b-4087-a52b-d12c8507c059.mp4

Also, there is no ability to disable `OnClickOutside` and `OnBackPress` .
```kotlin
object NonDismissableBottomSheet : DestinationStyle.BottomSheet {
    override val properties = BottomSheetProperties(
        dismissOnClickOutside = false,
        dismissOnBackPress = false,
    )
}
```

**Comment by ghasemdev** [comment]
Another question is how to open a bottom sheet completely?

**Comment by raamcosta** [comment]
Hi @ghasemdev! Thanks for reporting. 

The issue here is with Accompanist Navigation Material which we use to offer this functionality.
Your best bet is to open the same issue on their repo.

But actually, I see these issues that are already open and are related:

https://github.com/google/accompanist/issues/724
https://github.com/google/accompanist/issues/730

This said I will close the issue as it is not an issue with Compose Destinations. Let me know if that's ok with you.

**Comment by UnFunnyGuy** [comment]
> Another question is how to open a bottom sheet completely?

you can use 

_skipHalfExpanded = true _

on your **bottomSheetState**
