### ISSUE TITLE
[Multiple NavHosts] Ability to control DestinationsNavigator injection

### ISSUE THREAD

**Issue by ptashcka** [raamcosta/compose-destinations#58]
Thanks for the great library.
Maybe it's possible already, but couldn't find something like that in docs.
Would be great to be able to inject specific DestinationsNavigator, not necessarily the one for current Destination.
Maybe something like this:
```
@Destination(navGraph = "root")
@Composable
fun Screen(@Destination(navGraph = "auth") navigator: DestinationsNavigator)
```
Same goes for NavController

**Comment by raamcosta** [comment]
Hi @ptashcka !

I'm not 100% sure I get your request 🤔 
The DestinationsNavigator should be the same no matter what and you just need to ask for it and the library will provide it.
Are you experiencing any issue with the navigator to make you think you don't have the correct one?

**Comment by ptashcka** [comment]
Maybe I misuse it, but here's what I've found in docs: 
> Note that DestinationsNavigator is meant only for navigating from one screen to another. If you need some kind of "top-level" navigation (example: Bottom navigation bar, App drawer, etc) you should use the same NavController instance you pass to DestinationsNavHost.

So I have both navigation between screens and in one of them - navigation using bottom bar. To achieve that I use two DestinationNavHosts, root and main navGraphs. 
I believe DestinationsNavigator injected depending on the destination, but if you want to navigate from main to one of root screens - this is not possible using injected navigator.

**Comment by raamcosta** [comment]
Ahh now I get it, you have multiple DestinationsNavHost calls. I got confused because it the code you posted you were using `navGraph` on the annotation and that shouldn't be used with multiple NavHost calls. That is because when you have multiple NavHosts then each of those needs a completely separate navigation graph and that is not what you achieve with the `navGraph` param of the annotation. The library will generate one root navigation graph "root" with all others nested.

Besides, I would like to ask, are you sure you need multiple NavHosts? Most use cases can be handled with a single NavHost. My comment you pulled from the wiki simply meant that when you need to navigate but you are not inside any specific screen Composable, then you need to get the NavController by calling `rememberNavController` and passing the result of that into the DestinationsNavHost call.

In the end, if you really need multiple NavHost calls, there is no way for the library to give you the navigator related with the other NavHost, because they are truly separate. 
But there is ofc a way for you to inject it. Usually there will be a place in your code where both of the Nav Graphs intersect (f.e you are on a Screen Composable that inside calls a DestinationsNavHost) and there you will have access to both NavControllers. Then when you call DestinationsNavHost, you need to manually call its Composables to manually pass the NavController from the parent NavHost or you can wrap that parent NavController into an interface and make that available for all annotated Composables via the `dependencyContainerBuilder` parameter of the DestinationsNavHost call.

Sorry for the long winded answer and please let me know if it helps you. I'm open to answering more questions and even show you an example with some code snippets.

I'll close the issue but comment below with your feedback 🙂

**Comment by ptashcka** [comment]
Quite the opposite, thanks for such detailed response :) 
I kinda feel that I'm doing something wrong here with 2 nav hosts. The use case is quite simple: I have several screens on the top level, one of which has a bottom bar navigation. So I use one navhost for the top level navigation and another one for bottom bar navigation.

**Comment by raamcosta** [comment]
Cool! 

Ok, then check this closed issue:
https://github.com/raamcosta/compose-destinations/issues/48

We go over some of the approaches and details we need to use bottom nav bar.
Please reach out if I can still help you any further!
