### ISSUE TITLE
Preserve top-level screens for bottom bar

### ISSUE THREAD

**Issue by risalfajar** [raamcosta/compose-destinations#585]
Maybe this is not directly tied to the library, but I've followed the guide in [here](https://composedestinations.rafaelcosta.xyz/common-use-cases/bottom-bar-navigation) and can't find out how to make the top-level screens not recreating every time I'm navigating to them.

Could anyone provide a guidance?

This could also be a useful addition to the docs since this is a common thing to do with bottom bar navigation.

**Comment by risalfajar** [comment]
Hello @raamcosta would you please help?

**Comment by raamcosta** [comment]
Hi!

what do you mean with recreating? The UI composable always does get recreated. You can save it’s state in a ViewModel.
You can check my sample folder included in this project. You can also do some research for official compose navigation and what works there will also work with compose destinations. You have the Destination.route to get a string route if needed.

This question is not directly related with Compose Destinations so that’s why I haven’t done more than what you found on documentation.
