### ISSUE TITLE
Combine Destination annotations

### ISSUE THREAD

**Issue by Iliasgx** [raamcosta/compose-destinations#590]
With the addition of `@Destination` on annotation classes, we can replace the `@Destination` with our annotation class to reuse the same setup.

It would be nice to combine multiple annotations to extract the common setup but still allow screen specific params by making the `Destination` annotation repeatable. Currently this will throw a `IllegalDestinationsSetup` as both destinations try to add the same route name.

Example:
```kotlin
@Destination(
    wrappers = [
        AuthWrapper::class
    ]
)
annotation class AuthDestination

@AuthDestination
@Destination(
    navArgsDelegate = SomeNavArgs::class
)
@Composable
fun SomeScreen() { ... }
```

**Comment by Iliasgx** [comment]
Sure this will work in this case, thank you!

I was more thinking about the `@Preview` way of Compose to combine them such as:

```kotlin
@Preview(name = "Font - Default", group = "Font Scale", fontScale = 1f)
@Preview(name = "Font - Large", group = "Font Scale", fontScale = 1.5f)
annotation class FontScalePreviews

@FontScalePreviews
@Preview(name="Another preview type")
@Composable
fun SomeComposable() { ... }
```

That would allow annotations for specific cases used around the app such as `@AuthenticatedDestination`, `@FlagSecureDestination` etc. But doesn't pollute the annotations with overrides for possible NavArgs or DestinationStyles that have nothing to do with the used annotation classes.

However, wonderful the combination with overrides is already possible!

**Comment by raamcosta** [comment]
The issue with repeatable Destination is that it means a different thing that is also possible with v2. You will be able to have multiple Destinations in a given Composable and we will generate one Destination for each of those.

So in our case 1 Destination annotation = 1 generated Destination. I like it better this way :) 

I don't fully understand this part though:
> But doesn't pollute the annotations with overrides for possible NavArgs or DestinationStyles that have nothing to do with the used annotation classes.

I don't see it as pollution at all, I think it makes it explicit what usages of that annotation can control. Because if my annotation already controls one aspect of the "Destination" concept, then it should not allow usages to override that aspect.
Any Destination annotation (no matter if mine or yours) is the same "concept" and this concept has many characteristics which you inherit implicitly or explicitly, so again, "nothing to do" is not really true, in my eyes it has everything to do with it!

**Comment by raamcosta** [comment]
One thing that may not have been clear, is that you can have any number of levels of this, so for example, lets say you want all your annotations to be Dialogs (yes, stupid example ahah)

```kotlin
@Destination(style = DestinationStyle.Dialog::class)
annotation class DialogDestination(
    val navArgsDelegate: KClass<*> = Nothing::class,
    val wrappers: Array<KClass<out DestinationWrapper>> = [],
)

@DialogDestination(
    wrappers = [
        AuthWrapper::class
    ]
)
annotation class AuthDestination(
    val navArgsDelegate: KClass<*> = Nothing::class,
)

@AuthDestination(
    navArgsDelegate = SomeNavArgs::class
)
@Composable
fun SomeScreen() { ... }
```

**Comment by Iliasgx** [comment]
@raamcosta Does this require a special setup for multi-module projects? When the `@AuthDestination` annotation class is located in another module, the destinations I annotate with it are no longer generated.

**Comment by raamcosta** [comment]
Hmm try adding retention BINARY to AuthDestination, otherwise annotations are not really present to other modules.

But, I suspect it still won’t work, no.

FWIW, on v2 you’ll be able to add wrappers in the module that’s importing the destinations.

**Comment by raamcosta** [comment]
I mean this to your AuthDestination annotation:

`@Retention(AnnotationRetention.BINARY)`
