### ISSUE TITLE
[Question] How to navigate from ViewModel?

### ISSUE THREAD

**Issue by rovkinmax** [raamcosta/compose-destinations#594]
Hello!
Do you have an understanding of how to implement navigation from a ViewModel? I've studied the documentation and examples, but they all describe quite simple cases where all the navigation is done within compose functions. In slightly more complex applications, at least in my case, a click on a UI element can hide a lot of logic (form validation, permissions checking, network requests, etc.), and to navigate further, the ViewModel needs to expose something to let the compose function know that it's time to change the screen. May be you have some workaround for that?

**Comment by raamcosta** [comment]
Hi @rovkinmax !

First of all, I should mention that this is not recommended by Google and Android architecture guidelines. Their opinion is that navigating is strictly a UI responsibility and instead of thinking in these terms, you should instead change some state in the VM that makes the UI want to navigate (f.ex `loggedIn = true` would make the UI navigate forward from the login screen).
They also mention that for some screen sizes a navigation action may be performed in a different way, such as with item/detail on a tablet, where you'd want to show a different content in the "detail" part instead of navigating to it.

That said, I too think that for most apps, doing it will be just fine, so I won't tell you to do it or not to do it.

If you do want to do it, I should also tell you that this is actually not related to Compose Destinations. Since we depend on the official library, we inherit most architectural aspects of it.
So any solution out there that would work for the official lib, will also work for Compose Destinations.

AFAIK, the only way to achieve this is to have some kind of navigator to pass to your ViewModels. The thing is that this navigator cannot hold any reference to the Activity (or any other component that internally holds a reference to it) so that we don't cause memory leaks. So the way to do this is to have this navigator receive navigation events and propagate them to a "listener" (or collector in "flows" terminology) in your top level Composable, probably where you call DestinationsNavHost.
Then this "collector" can make the actual navigation call using the NavController it has access to.

So, you have to model navigation as some kind of sealed interface, pass them through a "Navigator" that just emits to SharedFlow (f.ex) and the collector of that flow does the actual navigation based on the type of event received.

Hope this is helpful! Let me know :)
