### ISSUE TITLE
ModuleRegistryKt is defined multiple times in Multi-Module project

### ISSUE THREAD

**Issue by nazarabd3005** [raamcosta/compose-destinations#597]
recently, I decided to migrate from v1 to v2, but whenever I try to build an application module always get this error:
`
Type _generated._ramcosta._composedestinations._moduleregistry.LiveLiterals$_ModuleRegistryKt is defined multiple times: .../build/.transforms/63279b7aaff76c785cd8429898cf01da/transformed/debug/debug_dex/_generated/_ramcosta/_composedestinations/_moduleregistry/LiveLiterals$_ModuleRegistryKt.dex, .../build/.transforms/aaa2c3593294b38efdcc69153b86f08f/transformed/debug/debug_dex/_generated/_ramcosta/_composedestinations/_moduleregistry/LiveLiterals$_ModuleRegistryKt.dex`
and this is a Gradle configuration for both affected library module

```
{
   namespace = "id.kesia.feature.home"

    ksp {
        arg("compose-destinations.codeGenPackageName","id.feature.home")

    }
 }  
```
    
 
```
 { 
 namespace = "id.kesia.feature.profile"
    ksp {
        arg("compose-destinations.codeGenPackageName","id.feature.profile")

    }
   }
```

Can you help me about what caused this issue?
I use 
Version v2.0.0-alpha02
Android studio Iguana
Compose 1.6.3

**Comment by raamcosta** [comment]
Hi @nazarabd3005 ! 👋 

Thank you so much for both taking the time to try v2 and to leave very important feedback 🙏 

I understand the issue, I am just wondering why this doesn't happen in the projects I tried it in. I guess it may be due to dex related configurations or maybe I have to make a release build to have this happen 🤔 

In any case, I will make it so these files are generated with different names!
I'll let you know when I release a new version with the fix!

Btw, how did migration go? Was it easy? Was the migration guide helpful? Thank you again!

**Comment by nazarabd3005** [comment]
Hi @raamcosta 
You're welcome! I appreciate your thoroughness in troubleshooting.
Regarding the migration, it went smoothly overall. The migration guide was indeed helpful in navigating the process. Thanks for checking in!

**Comment by raamcosta** [comment]
Glad to hear.

New version is building, should be up in like 30min or so.

Version: 2.0.0-alpha03

**Comment by raamcosta** [comment]
Artifacts are up! Please let me know if this is fixed :)

**Comment by nazarabd3005** [comment]
Hi @raamcosta 
already downloaded the update and it fixed the issue 👍 , 
Thanks for the update
