### ISSUE TITLE
Expected NavGraphSpec

### ISSUE THREAD

**Issue by Velord** [raamcosta/compose-destinations#607]
https://composedestinations.rafaelcosta.xyz/v2/multi-module-setup
According to that documentation, I wrote 2 graphs:

- MainGraph. app module
- BottomNavigationGraph. other module

```kotlin
private const val MAIN_GRAPH = "main_nav_graph"
@NavHostGraph(
    defaultTransitions = DefaultTransitions::class,
    route = MAIN_GRAPH,
    visibility = CodeGenVisibility.INTERNAL
)
annotation class MainGraph {
    @ExternalNavGraph<BottomNavigationGraph>(start = true)
    companion object Includes
}

private const val BOTTOM_NAVIGATION_GRAPH = "bottom_navigation_graph"
@NavGraph<ExternalModuleGraph>(
    route = BOTTOM_NAVIGATION_GRAPH,
    start = true,
    navArgs = Nothing::class,
    deepLinks = []
)
internal annotation class BottomNavigationGraph
```

This line of code: `@ExternalNavGraph<BottomNavigationGraph>(start = true)` tells
```
Expected NavGraphSpec
Found BottomNavigationGraph
```

I tried add/remove CodeGenVisibility.INTERNAL to BottomNavigationGraph.
I tried add/remove internal visibility to class itself.
And of course I compiled project before trying to add graph in another.

What am I missing ?

**Comment by raamcosta** [comment]
Hi @Velord 👋 

In your feature modules you can have sub graphs that are not part of the modules public API, since they’re nested in the one public one that gets imported in the main module.
But you’re right, you cannot use it for graphs that are part of the module’s public API, or in other words, graphs that should be exposed to other modules.
