### ISSUE TITLE
NavGraphArhs are visible only in "start" destination

### ISSUE THREAD

**Issue by KarolCieslar** [raamcosta/compose-destinations#633]
Here is my SettingsGraphArgs:
![image](https://github.com/raamcosta/compose-destinations/assets/5437671/c292a1d9-3c80-4a81-a474-f978c3ae13d8)

Here is my TempLockScreen (with @Destination(SettingsGraph)): 
![image](https://github.com/raamcosta/compose-destinations/assets/5437671/593d200b-42f9-4f9c-ab6a-7d3af3606398)

Here is my SettingsScreen (with @Destination(SettingsGraph) AND with start=true flag): 
![image](https://github.com/raamcosta/compose-destinations/assets/5437671/1b5b0bca-5bfd-4872-94b8-8b86da2ba4ee)

ViewModel of SettingsScreen: 
![image](https://github.com/raamcosta/compose-destinations/assets/5437671/23900d7a-3f68-4e8d-9a07-2569afead9df)

I use this code to navigate to Graph
`navigator.navigate(
                                            SettingsNavGraph(SettingsGraphArgs(userCard = currentCard.owner))
                                        )`

My NavGraphs arguments is empty when i try to get it from TempLockScreen but is visible from SettingsScreen. 
Is something what i am doing bad?

**Comment by raamcosta** [comment]
Hi!

NavGraph args are a bit tricky with official Compose Navigation as well. You need the back stack entry correspondent to the nav graph to make sure you'll have the args. If you navigate directly to another graph screen that is not the start one, the args will also not be there. That's why Compose Destinations APIs return nullable type in this case.

So, this is expected and how it works with official navigation library as well. You'll need to adapt to it.

**Comment by raamcosta** [comment]
See also here:
https://composedestinations.rafaelcosta.xyz/v2/arguments/navigation-arguments#navgraph-navigation-arguments

>NAV GRAPH ARGUMENTS ARE ALWAYS NULLABLE
Navigation arguments of nav graphs are tricky. They will be present if you navigate to the graph itself (for above example, doing navigator.navigate(ProfileNavGraph(id = "some id"))) and they will not be present if you navigate to one of its destinations directly.
This is how official compose navigation works as well, Compose Destinations makes it clear by returning nullable.
If you know in your case you always navigate to the Graph, you can do requireNavGraphArgs instead which will throw an exception instead of returning nullable type.

**Comment by KarolCieslar** [comment]
So i have to navigate to NavGraphs every time when i want to retrive NavGraphsArgs?
For example: I have LoginNavGraphs where i have LoginDestination(start), ForgotPasswordDestination, RegisterDestination. 
App start and i navigate to LoginNavGraph (i have arguments filled) then I want to redirect user to ForgotPasswordDestination with LoginNavGraph arguments so how i can navigate to this destination with arguments?

Sorry for my english ;/

**Comment by KarolCieslar** [comment]
@raamcosta can you tell me how i can do this? [https://github.com/raamcosta/compose-destinations/issues/633#issuecomment-2114107486](https://github.com/raamcosta/compose-destinations/issues/633#issuecomment-2114107486)

**Comment by raamcosta** [comment]
You can also get a hold of the `NavBackStackEntry` correspondent to your NavGraph, and that one will contain all nav graph arguments. 

Something like this:

```kotlin
destinationsNavigator.getBackStackEntry(ProfileNavGraph)?.navGraphArgs<ProfileNavGraphArgs>()
```

**Comment by KarolCieslar** [comment]
> You can also get a hold of the `NavBackStackEntry` correspondent to your NavGraph, and that one will contain all nav graph arguments.
> 
> Something like this:
> 
> ```kotlin
> destinationsNavigator.getBackStackEntry(ProfileNavGraph)?.navGraphArgs<ProfileNavGraphArgs>()
> ```

How about get arguments in ViewModel?
