### ISSUE TITLE
Instant navigation after result callback.

### ISSUE THREAD

**Issue by jahongir9779** [raamcosta/compose-destinations#64]
Hi, I'm not sure if this can be done at all but I was wondering, is it possible avoiding the composition of the resultRecipient screen somehow if I'm navigating to another destination after the result is received? 
For example, I have LoginDestination, SmsConfirmationDestination and HomeDestination.

What I want: User enters phone number, opens SmsConfirmationScreen with result callback. After the result is received in the LoginDestination it navigates to HomeScreen.  User should see HomeDestination after SmsConfirmationScreen.

What I'm having: When the result is received from SmsConfirmationDestination LoginDestination UI is shown for a moment and then navigation to HomeDestination is made...

**Comment by raamcosta** [comment]
Hi @jahongir9779 !

It sounds like in your case, you just want to navigate from SmsConfirmation to Home directly, right?
Instead of sending a result back to login screen.

It really depends on what UX you’re trying to build. Results work well here if your SmsConfirmation is a modal like a dialog or a bottom sheet. Then it makes sense that the Login UI is still shown briefly, maybe even show some kind of loading indicator while the user is being logged in. If SmsConfirmation is just a step in a login flow, then to me it makes sense to navigate directly to the next screen. And then maybe show the loading indicator inside SmsConfirmation screen in this case.

What do you think of this?

**Comment by jahongir9779** [comment]
Yeah the SmsConfirmation screen is used in multiple places so I built it with resultBackNavigator... Maybe showing a loading is a good idea, thanx

**Comment by raamcosta** [comment]
Or you could potentially have different destinations using the same content Composable.
So each Destination would call that same SmsConfirmationContent compostable passing in a different lambda for handling the result in a different way.

**Comment by jahongir9779** [comment]
Nice, I'll give it a try, thanx for a detailed advice :)
