### ISSUE TITLE
popUpTo matches navArgs exactly

### ISSUE THREAD

**Issue by cwsiteplan** [raamcosta/compose-destinations#646]
Hi,

i have following backstack:

Root -> List -> Detail -> Setup

on setup finish i want to navigate back to the list, but this time the list-destination is called with some additional navArgs (id of the element which should be initially scrolled to).

using `navigate(List(id= 123)) { popUpTo(List.route, inclusive = true)} `
does not work as i cannot find the backstack entry with the new args and just adds the new destination on the stack.

Were there considerations to not exactly match route (params) and just use the destination "root" ?

**Comment by raamcosta** [comment]
Can you show me the exact code to navigate and pop up that you’re trying?

**Comment by cwsiteplan** [comment]
i'm using
`    navigate(direction = destination, builder = {
            this.popUpTo(destination.route, popUpToBuilder = {
                this.inclusive = true
            })
    })
`

**Comment by raamcosta** [comment]
Yeah, so `Direction` has information about nav args (that's why when you have a Destination and invoke it, it gives you a Direction you can then pass to navigate to). `Route` doesn't.

Your extension function doesn't work because you're navigating to a `Direction`  (even though you're calling it "destination") and trying to pop it up from the back stack.

What you need to do is:

```kotlin
navigator.navigate(YourDestination(args) {
        popUpTo(YourDestination) {
            inclusive = true
        }
}
```

**Comment by cwsiteplan** [comment]
thanks for the clarification - will try that 👍
