### ISSUE TITLE
Multiple NavGraphs with shared routes on V2

### ISSUE THREAD

**Issue by Lisomatrix** [raamcosta/compose-destinations#649]
Hi,

I'm changing from 1.10.2 to 2.1.0-beta09 and I'm having some difficulties changing to the new version.

In the app I have 5 Nested Graphs all of them share the same pages, and the start page changes for all of them. Each nested graphs represents a tab in the bottom bar each having their own backstack. For this, in V1 I would add all the routes in each graph dynamically using the following:

```
private fun addCommonDestinations(destinations: MutableList<DestinationSpec<*>>) {
        home.destinationsByRoute.forEach { destinations.add(it.value) }
        shop.destinationsByRoute.forEach { destinations.add(it.value) }
        ...
    }
```

For each graph I would add the destinations
```
val homeRoot = object : NavGraphSpec {

        override val route: String = "home_root"
        override val startRoute: Route = HomeRootDestination routedIn this
        override val destinationsByRoute: Map<String, DestinationSpec<*>>
            get() {
                val destinations = mutableListOf<DestinationSpec<*>>()

                addCommonDestinations(destinations)

                return destinations
                    .routedIn(this)
                    .associateBy { it.route }
            }
    }
```

And finally merge them into nested nav graphs
```
val mainRoot = object : NavGraphSpec {

        override val route: String = "main_root"
        override val startRoute: Route = homeRoot
        override val destinationsByRoute = emptyMap<String, DestinationSpec<*>>()

        override val nestedNavGraphs = listOf(
            homeRoot,
            shopRoot,
            wishlistRoot,
            profileRoot,
            dropsRoot,
        )
    }
```

this would result in a route for each nested nav graph like:
home_root/product_detail
shop_root/product_detail
wishlist_root/product_detail
...

However, in the V2 I'm lacking the functions routedIn and within. 
What I was able to do so far was creating the module destinations and include them in separated Graphs like the following:

```
@NavHostGraph
annotation class MainGraph

@NavGraph<MainGraph>(
    start = true,
    route = "home"
)
annotation class HomeGraph {

    @ExternalModuleDestinations<AddressesModuleDestinations>
    @ExternalModuleDestinations<AuthModuleDestinations>
    @ExternalDestination<HomeRootDestination>(start = true)
    ...
    @ExternalModuleDestinations<ProductdetailModuleDestinations>
    @ExternalModuleDestinations<ProfileModuleDestinations>
    @ExternalModuleDestinations<SearchModuleDestinations>
    companion object Includes
}

@NavGraph<MainGraph>(
    start = true,
    route = "shop"
)
annotation class ShopGraph { ... }

...
```

However, in this case I get conflicts with the route names, and I haven't found any way to prefix the routes with their module name.

Another alternative I explored was to use a single NavGraph similar to before:

```
@NavHostGraph
annotation class RootGraph {
    @ExternalModuleDestinations<AddressesModuleDestinations>
    @ExternalModuleDestinations<AuthModuleDestinations>
    @ExternalModuleDestinations<BlogModuleDestinations>
    @ExternalModuleDestinations<CheckoutModuleDestinations>
    @ExternalModuleDestinations<CollectionsModuleDestinations>
    @ExternalModuleDestinations<ExclusiveaccessModuleDestinations>
    @ExternalDestination<HomeRootDestination>(start = true)
    @ExternalModuleDestinations<LivemeupModuleDestinations>
    @ExternalModuleDestinations<LookbookModuleDestinations>
    @ExternalModuleDestinations<LoyaltyModuleDestinations>
    @ExternalModuleDestinations<OnboardingModuleDestinations>
    @ExternalModuleDestinations<ProductdetailModuleDestinations>
    @ExternalModuleDestinations<ProfileModuleDestinations>
    @ExternalModuleDestinations<ReviewsModuleDestinations>
    @ExternalModuleDestinations<SearchModuleDestinations>
    @ExternalModuleDestinations<WishlistModuleDestinations>
    companion object Includes
}
```

While I was able to make the multiple backstacks work, I'm unable to know what is the current tab I'm currently in. The the nested graphs I could check by the current nestedGraph, but having a single Graph I'm not sure how I would do it

**Comment by raamcosta** [comment]
Hi 👋 

`routedIn` and `within` APIs were removed on v2. They were a sign of me trying to help in this very specific use case but giving up on type safety and "Compose Destinations way" to do it.

You can read about it here: (point 14)
https://composedestinations.rafaelcosta.xyz/migrating-to-v2#14-if-using-routedin-within-or-withdeeplinks-apis

To make one Composable Destination part of multiple graphs, you can now annotate it with multiple graph annotations if the Composable is declared in the same module as the graphs it wants to belong to. If it's not, you should expose normal Composable without being tied to navigation, and then on the module that knows about all the graphs, create the Destination annotated with multiple graph annotations. Then it just calls into the Composable.

This will generate one Destination for each combination of Nav Graph, and you'll be able to manage it in a more type safe way (since you cannot make mistakes with `within` API and use a Nav Graph which that destination is not a part of, which would fail at runtime).

Let me know if this helps!
