### ISSUE TITLE
Proper way of injecting DestinationsNavigator into ViewModel

### ISSUE THREAD

**Issue by cypis** [raamcosta/compose-destinations#65]
Hi, I would like to navigate to certain screen directly from ViewModel. 
How do I inject `DestinationsNavigator` properly into ViewModel using Hilt, I can't find a way to get an instance of it.

**Comment by raamcosta** [comment]
Hi @cypis ! 👋 

So you should think of this `DestinationsNavigator` as you would for `navController` since it internally uses that. What I mean is that you shouldn't be passing it into ViewModel.

If you really want to navigate from the ViewModel, what you need to do is to emit some event in the ViewModel and consume it in the Composable.

Example:

```kotlin
@Destination
@Composable
fun MyScreen(
    navigator: DestinationsNavigator,
    viewModel: MyScreenViewModel = hiltViewModel() //example if you use Hilt
) {
    LaunchedEffect(Unit) {
        viewModel.navigationEvents.collect { direction -> Direction
            navigator.navigate(direction)
        }
    }
}
```

Take this with a grain of salt, the code was not tested, I just wrote it here all from the top of my head.

Sort of how they do it [here](https://proandroiddev.com/jetpack-compose-navigation-architecture-with-viewmodels-1de467f19e1c), but you can be a bit more type safe and use a `Direction` instead of a string. (to create a direction, simply call the invoke function of the Destination you want to navigate to, or if the Destination has no arguments, then the Destination itself is a Direction).

**Comment by raamcosta** [comment]
Hope this was helpful @cypis.

I'll close this but feel free to answer below or open a new issue if there is anything else I can help you with!
