### ISSUE TITLE
Material3 Bottomsheets support

### ISSUE THREAD

**Issue by vityokkv73** [raamcosta/compose-destinations#689]
As per the [documentation](https://composedestinations.rafaelcosta.xyz/styles-and-animations#bottomsheet-style), to work with bottom sheets as navigation destinations, we need to include dependencies for `androidx.compose.material.navigation.ModalBottomSheetLayout `and `androidx.compose.material.navigation.rememberBottomSheetNavigator`. However, if our project uses `material3` components instead of `material` ones, Android Studio issues warnings about potential problems:
> Using a material import while also using the material3 library
> Inspection info: material and material3 are separate design system libraries that are incompatible with each other, as they have their own distinct theming systems. Using components from both libraries concurrently can cause issues: for example material components will not pick up the correct content color from a material3 container, and vice versa.

Is there a way to use this library with `material3` bottom sheets as we did with `material`?

**Comment by vityokkv73** [comment]
I reviewed the code for `ModalBottomSheetLayout` and `BottomSheetNavigator` from the `androidx.compose.material.navigation` package, and noticed that they rely on dependencies from the `material` library, such as:
```
import androidx.compose.material.MaterialTheme
import androidx.compose.material.ModalBottomSheetDefaults
import androidx.compose.material.ModalBottomSheetLayout
import androidx.compose.material.contentColorFor
import androidx.compose.material.ModalBottomSheetState
import androidx.compose.material.ModalBottomSheetValue
import androidx.compose.material.rememberModalBottomSheetState
```
Is there any possibility that we might see an implementation of `ModalBottomSheetLayout` and `BottomSheetNavigator` utilizing `material3` components, integrated into the `compose-destinations` library? Perhaps something like an add-on, such as `io.github.raamcosta.compose-destinations:model-bottom-sheet:<version>`?

**Comment by raamcosta** [comment]
Hi 👋

We are just making use of the what is officially available. If you stay on the official library world, you’d have the same dependencies we use here.
I would just suppress the warning, for bottom sheet destinations we need to use “navigation material”, and as far as I know that dependency is not intrinsically tied to material 2 or 3. So to me that warning is just wrong.

Internally maybe they do use material 2 bottom sheet or maybe not, I honestly don’t know or care since that is and should be abstracted away from us.
