### ISSUE TITLE
NestedGraph with v2

### ISSUE THREAD

**Issue by Mcmillian** [raamcosta/compose-destinations#698]
Hi, I'm trying to use v2 and I'm having trouble with nested navigation.
In RootGraph, I have a MainScreen with four Screens contained in the MainGraph.
`@NavGraph<RootGraph>
annotation class MainGraph(
val start: Boolean = false
)`
In MainScreen, how should I use MainGraph? I tried using DestinationsNavHost, but the navGraph parameter says the type doesn't match. I didn't find anything in the sample project, maybe I missed it.

I noticed a similar issue [#604](https://github.com/raamcosta/compose-destinations/issues/604), but he ended up using two DestinationsNavHosts to solve the problem, which doesn't seem like best practice?

Can you give me an example? Thanks

**Comment by raamcosta** [comment]
Hi!

if you want to pass this graph to a NavHost, then it cannot have a parent - this is done by using a `@NavHostGraph` annotation instead of `@NavGraph<RootGraph>`.

read more here:
https://composedestinations.rafaelcosta.xyz/v2/defining-navgraphs#defining-navigation-graphs-1

If you’re migrating to v2, I recommend following this  guide:
https://composedestinations.rafaelcosta.xyz/migrating-to-v2

**Comment by Mcmillian** [comment]
It seems that multiple NavHosts are not recommended in v2? What should I do to best implement nested navigation?

**Comment by raamcosta** [comment]
It was never recommended, but there are some reasons to do it. If you have it setup like that and it works well for you, I wouldn’t bother changing it 🙂

**Comment by Mcmillian** [comment]
I have been researching for another day, but still haven't found how to implement nested navigation with single DestinationNavHost on v2. Can you give me an example？
