### ISSUE TITLE
Make Result back feature work between different modules

### ISSUE THREAD

**Issue by margarita-v** [raamcosta/compose-destinations#70]
For example, I have independent features `feed` and `catalog` in different modules which should be independent from each other. Currently it's impossible to get result in feed from catalog:
```
@Destination
@Composable
fun FeedScreen(
    // CatalogScreenDestination is built in catalog module and unavaliable in feed
    resultRecipient: ResultRecipient<CatalogScreenDestination, Boolean>
) {
```
The only workaround is to place CatalogScreen to some common module which could be available in `feed`.
Could be nice to define the build path manually:
```
// define CatalogScreen in catalog module but the destination is generated in common navigation module
@Destination(
  module = "../navigation" // and the rest of the path is the same: build/generated/ksp/debug/kotlin
)
@Composable
fun CatalogScreen()
```

UPD The workaround with a common module is currently impossible because of https://github.com/raamcosta/compose-destinations/issues/59. Now the `ResultRecipient` approach works only for screens in the same module

**Comment by raamcosta** [comment]
This is more difficult issue. I know that nav result only works within the same module, but it is a tradeoff with type safety.

I will explore solutions/improvements to this soon (hopefully) and I will keep this post updated.

Thank you so so much @margarita-v 🙂 it really means a lot!
I noticed you explored quite a bit of internal code, let me known if you ever want to contribute!

**Comment by margarita-v** [comment]
Thank you too @raamcosta , I'd be happy to help when possible 👍

**Comment by Voroz** [comment]
@raamcosta I have the same problem. I separated my project into two library modules and I can't find a good way to navigate between them now. If I could make it so everything is built into the core module instead I could access it from all of my modules. Let me know if you have any possible solutions to this. Other than this issue it's a great library!

**Comment by raamcosta** [comment]
@Voroz this issue is not about navigation between modules, this is just about "result back" feature between modules.
Navigation between modules, work as expected: you need to delegate navigation to the "navigation" module, i.e, you pass a lambda / interface implementation to the feature modules screens from the module that calls `DestinationsNavHost`.

You can check this fork of Philipp Lackner's "CalorieTracker" repo: https://github.com/raamcosta/CalorieTracker for an example where I have a common navigator that implements all interfaces declared on each feature module and pass that as a dependency in `dependenciesContainerBuilder` parameter of `DestinationsNavHost` call.

Btw @Voroz I took a look at your repository and for multi module projects you need to use a couple configurations at gradle level. Make sure you look at gradle build files from the repository I linked above.
Read about these configs here: https://composedestinations.rafaelcosta.xyz/codegenconfigs#multi-module-configs

**Comment by Voroz** [comment]
@raamcosta My bad, I did not read the question carefully enough. Thanks for your reply and your time to have a look at my project. I've implemented something similar to the CalorieTracker app now. If you have time, let me know what you think. Are you contactable by any other means? I don't want to add any more noise to this current issue thread.

**Comment by raamcosta** [comment]
We'll have a solution in the next release, pay attention to release notes :)

**Comment by raamcosta** [comment]
@margarita-v I'd love it if you could test the solution present in 1.5.6-beta! 🙏

**Comment by margarita-v** [comment]
@raamcosta Thank you, I've checked, it perfectly works 🔥 Also wanted to ask you, why can't we use Unit as a result according to `InitialValidator.validateResultType`? Should I open a separate issue (minor, but could be useful as a sign of completed work without data)?

**Comment by raamcosta** [comment]
Yeah, please open it as an enhancement :) I need to check it to be sure, but I believe we can support that easily.

**Comment by raamcosta** [comment]
Glad the solution is good enough for you btw! :)

**Comment by hozrotbelal** [comment]
Make Result back feature work between different modules....Please write the code from different module such as: ScreenA,ScreenB and ScreenC.   ScreenB and ScreenC is different Module. I want to result back ScreenA but how it will be solved it?
@Destination()
@Composable
fun VendorProfileScreen(
    navBackStackEntry: NavBackStackEntry,
    resultRecipient: ResultRecipient<ScreenB, Boolean> // this line how to include ScreenC
    )
    This is the scenario. @raamcosta
