### ISSUE TITLE
Current destination is not saved when process death happens

### ISSUE THREAD

**Issue by raheemadamboev** [raamcosta/compose-destinations#71]
When process death happens, it won't get navigated to last destination. It just starts from the start destination.

Is there any solution to solve this problem?

**Comment by raamcosta** [comment]
Hi @raheemadamboev !

This is not true at all 😄 
In fact, even yesterday I tested some stuff regarding process death. It must be something on your end. Maybe the way you're testing this?

Also keep in mind that this libray uses the Official Jetpack Compose Navigation library, so it would be really weird for this to be the case.

Because of this, I will close the issue, but please, let me know if you manage to find what is the actual cause for your issue and I can help you do that if you want.

**Comment by raheemadamboev** [comment]
Sorry, it is very weird. It started working perfect now. 

I didn't change neither code nor testing method. I just rechecked it after your comment and it started working somehow. Thank you for this amazing library!
